"""Synth Index clients and contracts; backend routes remain the wire authority."""

from .agent_policy import IndexAccessPolicy
from .catalog import (
    Capabilities,
    CollectionGrant,
    CollectionGrantSpec,
    Collections,
    ContestEntry,
    ContestView,
    IndexUsageSummary,
    Leaderboard,
    MyRewards,
    PrivatePromoCredit,
    ProfileView,
    PromoCreditSummary,
    RewardAward,
    TagRegistry,
)
from .contracts import ContributionReference
from .contributions import (
    ContributionDraft,
    ContributionUploadPrepared,
    ContributionUploadSpec,
    ResearchDraftSpec,
    ResearchSource,
)
from .errors import IndexErrorCode, index_error_code
from .lifecycle import (
    Assessment,
    ContributionView,
    MeView,
    PublicationSpec,
    PublicationStatus,
    ReviewDecision,
    ReviewSpec,
    RevisionCreateSpec,
    RevisionView,
    WithdrawalSpec,
)
from .package import ContributionPackage
from .public import AsyncPublicIndexClient, PublicIndexClient
from .search import (
    ContentsResult,
    ContentsSpec,
    PublicSearchResult,
    Search,
    SearchCancellation,
    SearchEvent,
    SearchEventKind,
    SearchEventPage,
    SearchExecutionLimits,
    SearchExecutionVersions,
    SearchFailure,
    SearchMode,
    SearchPartialReason,
    SearchResult,
    SearchSpec,
    SearchState,
    SearchUsage,
)
from .submission import ContributionSubmission, ContributionSubmitSpec, RevisionStatus

__all__ = [
    "Assessment",
    "AsyncPublicIndexClient",
    "Capabilities",
    "CollectionGrant",
    "CollectionGrantSpec",
    "Collections",
    "ContentsResult",
    "ContentsSpec",
    "ContestEntry",
    "ContestView",
    "ContributionDraft",
    "ContributionPackage",
    "ContributionReference",
    "ContributionSubmission",
    "ContributionSubmitSpec",
    "ContributionUploadPrepared",
    "ContributionUploadSpec",
    "ContributionView",
    "IndexAccessPolicy",
    "IndexErrorCode",
    "IndexUsageSummary",
    "Leaderboard",
    "MeView",
    "MyRewards",
    "PrivatePromoCredit",
    "ProfileView",
    "PromoCreditSummary",
    "PublicIndexClient",
    "PublicSearchResult",
    "PublicationSpec",
    "PublicationStatus",
    "ResearchDraftSpec",
    "ResearchSource",
    "ReviewDecision",
    "ReviewSpec",
    "RevisionCreateSpec",
    "RevisionStatus",
    "RevisionView",
    "RewardAward",
    "Search",
    "SearchCancellation",
    "SearchEvent",
    "SearchEventKind",
    "SearchEventPage",
    "SearchExecutionLimits",
    "SearchExecutionVersions",
    "SearchFailure",
    "SearchMode",
    "SearchPartialReason",
    "SearchResult",
    "SearchSpec",
    "SearchState",
    "SearchUsage",
    "TagRegistry",
    "WithdrawalSpec",
    "index_error_code",
]
