# FFT job config for Qwen/Qwen3-4B on Crafter SFT dataset

[job]
model = "Qwen/Qwen3-4B"
# If not provided via --data, set a relative dataset path here
# data = "../ft_data/qwen3_32b_ach_ge3_raw_filtered.jsonl"

[compute]
# Adjust as needed for your quota
gpu_type = "H100"
gpu_count = 1
nodes = 1

[data]
# Optional topology metadata (left empty for now)
topology = {}

[training]
mode = "sft_offline"
use_qlora = false

[hyperparameters]
# Minimal safe defaults; backend can override
n_epochs = 1
batch_size = 1
gradient_accumulation_steps = 16
sequence_length = 2048*2
learning_rate = 5e-6
warmup_ratio = 0.03
train_kind = "fft"

# Optional parallelism block example
#[hyperparameters.parallelism]
# tensor_parallel_size = 1
# pipeline_parallel_size = 1
