# Eval config for Groq Qwen3-32B
# Fields mirror run_eval.py expectations

# Required
task_app_url = "https://synth-laboratories--grpo-crafter-task-app-final-warming--ceb5b2.modal.run"
model = "qwen/qwen3-32b"
inference_url = "https://api.groq.com/openai"

# Optional
num_episodes = 20
max_turns = 10
concurrency = 10
# difficulty = "easy"
