"""Generated Managed Research actor model policy constants.

Source of truth: backend/packages/smr/config/actor_configurations/actor_role_gates.py

Regenerate: python -m synth_ai.managed_research.schema_sync
"""

from __future__ import annotations

from typing import Any

SMR_SHARED_TOP_LEVEL_AGENT_MODEL_VALUES: tuple[str, ...] = (
    "baseten/zai-org/GLM-5.2",
    "deepseek/deepseek-v4-flash",
    "deepseek/deepseek-v4-flash-direct",
    "deepseek/deepseek-v4-pro",
    "deepseek/deepseek-v4-pro-direct",
    "gpt-5.4-mini",
    "gpt-5.5",
    "gpt-5.6-luna",
    "x-ai/grok-4.3",
    "x-ai/grok-build",
)


SMR_ACTOR_MODEL_POLICY: tuple[dict[str, Any], ...] = (
    {
        "actor_type": "orchestrator",
        "actor_subtype": "main",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "moonshotai/kimi-k2.6",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "main",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "moonshotai/kimi-k2.6",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "task_completion",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "moonshotai/kimi-k2.6",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "run_completion",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "safety",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "objective",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "seraph",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "gardener",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "reviewer",
        "actor_subtype": "artifact_reviewer",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "moonshotai/kimi-k2.6",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "worker",
        "actor_subtype": "engineer",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.3-codex",
            "gpt-5.3-codex-spark",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "modal/zai-org/GLM-5.2-FP8",
            "moonshotai/kimi-k2.6",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "worker",
        "actor_subtype": "researcher",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "modal/zai-org/GLM-5.2-FP8",
            "moonshotai/kimi-k2.6",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
    {
        "actor_type": "worker",
        "actor_subtype": "artifact_builder",
        "permitted_models": [
            "baseten/zai-org/GLM-5.2",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-flash-direct",
            "deepseek/deepseek-v4-pro",
            "deepseek/deepseek-v4-pro-direct",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-luna",
            "moonshotai/kimi-k2.6",
            "x-ai/grok-4.3",
            "x-ai/grok-build",
        ],
    },
)


__all__ = ["SMR_ACTOR_MODEL_POLICY", "SMR_SHARED_TOP_LEVEL_AGENT_MODEL_VALUES"]
