from .auth import (
    is_api_key_header_authorized,
    normalize_environment_api_key,
    require_api_key_dependency,
)
from .client import TaskAppClient
from .config import EvalConfig, FilterConfig
from .contracts import (
    DatasetInfo,
    InferenceInfo,
    LimitsInfo,
    RolloutEnvSpec,
    RolloutMetrics,
    RolloutPolicySpec,
    RolloutRecordConfig,
    RolloutRequest,
    RolloutResponse,
    RolloutSafetyConfig,
    RolloutStep,
    RolloutTrajectory,
    RubricInfo,
    RubricSection,
    TaskAppEndpoints,
    TaskDescriptor,
    TaskInfo,
)
from .datasets import TaskDatasetRegistry, TaskDatasetSpec
from .errors import error_payload, http_exception, json_error_response
from .health import task_app_health
from .in_process import InProcessTaskApp
from .in_process_runner import (
    InProcessJobResult,
    merge_dot_overrides,
    resolve_backend_api_base,
    run_in_process_job,
    run_in_process_job_sync,
)
from .inference_api import InferenceAPIClient
from .json import to_jsonable
from .proxy import (
    extract_message_text,
    inject_system_hint,
    parse_tool_call_from_text,
    prepare_for_groq,
    prepare_for_openai,
    synthesize_tool_call_if_missing,
)
from .rubrics import (
    Criterion,
    Rubric,
    blend_rubrics,
    load_rubric,
    score_events_against_rubric,
    score_outcome_against_rubric,
)
from .server import (
    ProxyConfig,
    RubricBundle,
    TaskAppConfig,
    create_task_app,
    run_task_app,
)
from .trace_correlation_helpers import (
    build_trajectory_trace,
    extract_trace_correlation_id,
    include_event_history_in_trajectories,
    include_trace_correlation_id_in_response,
    validate_trace_correlation_id,
    verify_trace_correlation_id_in_response,
)
from .validators import (
    normalize_inference_url,
    validate_rollout_response_for_rl,
    validate_task_app_endpoint,
    validate_task_app_url,
)
from .vendors import (
    get_groq_key_or_503,
    get_openai_key_or_503,
    normalize_vendor_keys,
)

__all__ = [
    "normalize_inference_url",
    "validate_rollout_response_for_rl",
    "validate_task_app_url",
    "validate_task_app_endpoint",
    "task_app_health",
    "EvalConfig",
    "FilterConfig",
    "TaskAppEndpoints",
    "RolloutEnvSpec",
    "RolloutPolicySpec",
    "RolloutRecordConfig",
    "RolloutSafetyConfig",
    "RolloutRequest",
    "RolloutResponse",
    "RolloutTrajectory",
    "RolloutStep",
    "RolloutMetrics",
    "TaskDescriptor",
    "DatasetInfo",
    "RubricInfo",
    "RubricSection",
    "InferenceInfo",
    "LimitsInfo",
    "TaskInfo",
    "to_jsonable",
    "normalize_environment_api_key",
    "is_api_key_header_authorized",
    "require_api_key_dependency",
    "normalize_vendor_keys",
    "get_openai_key_or_503",
    "get_groq_key_or_503",
    "prepare_for_openai",
    "prepare_for_groq",
    "inject_system_hint",
    "extract_message_text",
    "parse_tool_call_from_text",
    "synthesize_tool_call_if_missing",
    "TaskDatasetSpec",
    "TaskDatasetRegistry",
    "Criterion",
    "Rubric",
    "load_rubric",
    "blend_rubrics",
    "score_events_against_rubric",
    "score_outcome_against_rubric",
    "TaskAppClient",
    "error_payload",
    "http_exception",
    "json_error_response",
    "run_task_app",
    "create_task_app",
    "RubricBundle",
    "ProxyConfig",
    "TaskAppConfig",
    "InferenceAPIClient",
    "InProcessTaskApp",
    "InProcessJobResult",
    "merge_dot_overrides",
    "resolve_backend_api_base",
    "run_in_process_job",
    "run_in_process_job_sync",
    "build_trajectory_trace",
    "extract_trace_correlation_id",
    "include_event_history_in_trajectories",
    "include_trace_correlation_id_in_response",
    "validate_trace_correlation_id",
    "verify_trace_correlation_id_in_response",
]
