# Crafter rollout config for GPT-OSS-120B served from OpenAI-compatible APIs.
# Replace the task_app_url with your deployed Crafter task app URL.
# The run stores full traces so we can keep the LLM reasoning for fine-tuning.

[eval]
app_id = "grpo-crafter"
task_app_url = "https://synth-laboratories--grpo-crafter-task-app-fastapi-app-dev.modal.run"
model = "openai/gpt-oss-120b"
seeds = [0, 1, 2]
max_turns = 10
concurrency = 1
env_name = "crafter"
policy_name = "crafter-react"
trace_format = "full"
return_trace = true

[eval.env_config]
env_params = { max_steps_per_episode = 10 }

[eval.policy_config]
provider = "groq"
model = "openai/gpt-oss-120b"
inference_url = "https://api.groq.com/openai"
temperature = 0.6
top_p = 0.9
max_tokens = 768
use_vision = false
image_only_mode = false
max_llm_calls = 10
