export const DEFAULT_API_TIMEOUT_MS = 15000
export const DEFAULT_HEALTH_TIMEOUT_MS = 5000
export const DEFAULT_AUTH_TIMEOUT_MS = 15000
export const DEFAULT_TRACE_TIMEOUT_MS = 20000
export const DEFAULT_OPENCODE_TIMEOUT_MS = 15000
export const DEFAULT_IMAGE_TIMEOUT_MS = 15000

export const SSE_RECONNECT_BASE_MS = 1000
export const SSE_RECONNECT_MAX_MS = 30000
export const SSE_RECONNECT_MULTIPLIER = 1.7
export const SSE_RECONNECT_JITTER_MS = 250
