# Evaluation config for gpt-4o-mini (vision)
# Collects traces for SFT training; legacy gpt-5-nano naming kept for convenience

[eval]
app_id = "grpo-crafter-task-app"
task_app_url = "https://synth-laboratories--grpo-crafter-task-app.modal.run"
model = "gpt-4o-mini-2024-07-18"
seeds = "0-99"
max_turns = 50
concurrency = 5
env_name = "crafter"
policy_name = "crafter-react"
trace_format = "structured"
return_trace = true

[eval.env_config]
env_params = {max_steps_per_episode = 50}

[eval.policy_config]
provider = "openai"
model = "gpt-4o-mini-2024-07-18"
temperature = 0.7
max_tokens = 512
use_vision = true
image_only_mode = false
use_tools = true
