# Evaluation config for Qwen2-VL via synth-ai hosted inference
# Collects vision traces for SFT training

[eval]
model = "Qwen/Qwen2-VL-7B-Instruct"
provider = "synth"  # Use synth-ai hosted inference

# Task app endpoint (local or hosted)
# task_app_url = "http://localhost:8000"  # Local
task_app_url = "https://synth-laboratories--grpo-crafter-task-app.modal.run"  # Hosted

# Vision settings (auto-detected from "qwen2-vl" in model name)
use_vision = true
image_only_mode = false  # Include both text + images

# Rollout settings
num_episodes = 100
max_steps_per_episode = 50
seeds = "100-199"  # Different seeds from gpt-5-nano for comparison

# Sampling parameters
temperature = 0.7
max_tokens = 512

# Trace collection
collect_traces = true
trace_db = "traces/qwen2vl_vision/rollouts.db"

# Tools
use_tools = true

# Parallel rollouts
parallel_episodes = 5

[task]
name = "crafter"
environment = "crafter-classic"

# Task-specific settings
[task.config]
seed_start = 100
max_episode_length = 256
render_size = [64, 64]  # 64x64 PNG images

