# Evaluation config for running Groq Qwen/Qwen3-32B against the Sokoban task app.

provider = "groq"
task_app_url = "http://127.0.0.1:8911"
model = "qwen/qwen3-32b"
seeds = [123]
max_turns = 60
concurrency = 1

[policy]
provider = "groq"
model = "qwen/qwen3-32b"
temperature = 0.2
top_p = 0.95
max_tokens = 8000
max_actions_per_call = 4
