# Generated by Forge scripts/export_contracts.py.
# Schema SHA256: e1ef9bd482d45c91eadccee902efe873c53b63a736a0f694a06223c95e37b8a9
"""Scoped scientific identities. See docs/contracts.md and SYN-3548.

Constraint vocabulary and canonical encoding retain backend contributions'
closed contracts. A reference expresses provenance, never access authority.
"""

from __future__ import annotations

import hashlib
import json
from typing import Annotated

from pydantic import BaseModel, ConfigDict, StringConstraints

Identifier = Annotated[
    str, StringConstraints(pattern=r"^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,127}$")
]
Digest = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]
Text = Annotated[str, StringConstraints(min_length=1, max_length=8000)]


class Contract(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)


def canonical_bytes(value: BaseModel | dict) -> bytes:
    document = value.model_dump(mode="json") if isinstance(value, BaseModel) else value
    return json.dumps(
        document,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def contract_digest(value: BaseModel | dict) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


class Scope(Contract):
    organization_id: Identifier
    project_id: Identifier


class ExactReference(Contract):
    authority: Identifier
    kind: Identifier
    record_id: Identifier
    revision: Identifier
    digest_sha256: Digest


class Producer(Contract):
    """Execution DTOs stay producer-owned; only exact opaque references live here."""

    authority: Identifier
    subject_id: Identifier
    execution: ExactReference | None = None
    context: ExactReference | None = None
    admission: ExactReference | None = None
    grant: ExactReference | None = None
    budget: ExactReference | None = None


class ForgeError(ValueError):
    def __init__(self, code: str, message: str):
        self.code = code
        super().__init__(message)
