# Generated by Forge scripts/export_contracts.py.
# Schema SHA256: 08a0735563a42e3a45b5497b552bb2b1ff122a630c121e2eed28167896adf8d3
"""Scoped scientific identities. See docs/contracts.md and SYN-3548.

Constraint vocabulary and canonical encoding retain backend contributions'
closed contracts. A reference expresses provenance, never access authority.
"""

from __future__ import annotations

import hashlib
import json
from typing import Annotated

from pydantic import BaseModel, ConfigDict, StringConstraints, model_validator

Identifier = Annotated[
    str, StringConstraints(pattern=r"^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,127}$")
]
Digest = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]
Text = Annotated[str, StringConstraints(min_length=1, max_length=8000)]


class Contract(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)


def canonical_bytes(value: BaseModel | dict) -> bytes:
    document = value.model_dump(mode="json") if isinstance(value, BaseModel) else value
    return json.dumps(
        document,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def contract_digest(value: BaseModel | dict) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


class Scope(Contract):
    organization_id: Identifier
    project_id: Identifier


ReferenceRecordId = Annotated[
    str,
    StringConstraints(
        pattern=r"^(?:[a-zA-Z0-9][a-zA-Z0-9_.-]{0,127}|intern-exec:[0-9a-f]{64})$"
    ),
]


class ExactReference(Contract):
    model_config = ConfigDict(
        json_schema_extra={
            "allOf": [
                {
                    "if": {
                        "properties": {"record_id": {"pattern": "^intern-exec:"}},
                        "required": ["record_id"],
                    },
                    "then": {
                        "properties": {
                            "authority": {"const": "mloky"},
                            "kind": {"const": "mloky_execution"},
                        }
                    },
                }
            ]
        }
    )
    authority: Identifier
    kind: Identifier
    record_id: ReferenceRecordId
    revision: Identifier
    digest_sha256: Digest

    @model_validator(mode="after")
    def native_execution_scope(self):
        if ":" in self.record_id and (self.authority, self.kind) != (
            "mloky",
            "mloky_execution",
        ):
            raise ValueError(
                "native Intern execution reference authority/kind mismatch"
            )
        return self


class Producer(Contract):
    """Execution DTOs stay producer-owned; only exact opaque references live here."""

    authority: Identifier
    subject_id: Identifier
    execution: ExactReference | None = None
    context: ExactReference | None = None
    admission: ExactReference | None = None
    grant: ExactReference | None = None
    budget: ExactReference | None = None


class ForgeError(ValueError):
    def __init__(self, code: str, message: str):
        self.code = code
        super().__init__(message)
