# Generated by Forge scripts/export_contracts.py.
# Schema SHA256: 08a0735563a42e3a45b5497b552bb2b1ff122a630c121e2eed28167896adf8d3
"""Private frozen selection and complete credit. See SYN-3597/SYN-3598.

These contracts cannot grant Index rights, seal a revision or approve release.
ContributionPackage v1 remains the separately validated public descriptor.
"""

from typing import Literal

from pydantic import Field, model_validator

from .contracts import Contract, Digest, ExactReference, Identifier, Text


class Credit(Contract):
    contributor_id: Identifier
    role: Literal["author", "data", "implementation", "method", "review", "funding"]
    upstream_contribution: ExactReference | None = None
    license: Text


class OutputAsset(Contract):
    asset_id: Identifier
    source: ExactReference
    digest_sha256: Digest
    license: Text

    @model_validator(mode="after")
    def exact_bytes(self):
        if self.digest_sha256 != self.source.digest_sha256:
            raise ValueError(
                "frozen-copy output must retain the consumed source digest"
            )
        return self


class ScientificExport(Contract):
    kind: Literal["scientific_export"] = "scientific_export"
    output_id: Identifier
    snapshots: tuple[ExactReference, ...] = Field(min_length=1, max_length=256)
    sources: tuple[ExactReference, ...] = Field(min_length=1, max_length=1024)
    assets: tuple[OutputAsset, ...] = Field(min_length=1, max_length=1024)
    credits: tuple[Credit, ...] = Field(min_length=1, max_length=256)
    recipe: ExactReference
    exporter: ExactReference
    # This is a proposal only. Index must independently approve disclosure.
    proposed_public_sources: tuple[ExactReference, ...] = Field(
        default=(), max_length=256
    )

    @model_validator(mode="after")
    def selected_identities(self):
        for values, label in (
            (self.snapshots, "snapshots"),
            (self.sources, "sources"),
            (tuple(item.asset_id for item in self.assets), "asset IDs"),
            (
                tuple(
                    (item.contributor_id, item.role, item.upstream_contribution)
                    for item in self.credits
                ),
                "credits",
            ),
        ):
            if len(values) != len(set(values)):
                raise ValueError(f"{label} must be unique")
        if not set(self.proposed_public_sources).issubset(self.sources):
            raise ValueError("public source proposals must be frozen selected sources")
        if any(
            ref.authority != "forge" or ref.kind != "snapshot" for ref in self.snapshots
        ):
            raise ValueError("exports select canonical frozen snapshots")
        return self


class SourceNotice(Contract):
    kind: Literal["source_notice"] = "source_notice"
    original: ExactReference
    replacement: ExactReference | None = None
    disposition: Literal["correction", "supersession", "retraction"]
    reason: Text
    pinned_releases: tuple[ExactReference, ...] = Field(min_length=1, max_length=1024)
    sources: tuple[ExactReference, ...] = Field(default=(), max_length=1024)

    @model_validator(mode="after")
    def immutable_releases(self):
        if self.original.authority != "forge":
            raise ValueError("notice requires an exact scientific source")
        if self.disposition != "retraction" and self.replacement is None:
            raise ValueError("correction or supersession requires a replacement")
        if any(ref.authority != "index" for ref in self.pinned_releases):
            raise ValueError("release notices refer to pinned Index revisions")
        if self.original == self.replacement:
            raise ValueError("replacement must differ from original")
        if self.replacement and (
            self.replacement.authority != "forge"
            or self.replacement.kind != self.original.kind
        ):
            raise ValueError("replacement must be the same scientific source kind")
        if len(set(self.pinned_releases)) != len(self.pinned_releases):
            raise ValueError("pinned releases must be unique")
        return self
