# Generated by Forge scripts/export_contracts.py.
# Schema SHA256: e1ef9bd482d45c91eadccee902efe873c53b63a736a0f694a06223c95e37b8a9
"""Retry identity, receipts and scoped event cursors. See docs/contracts.md."""

from typing import Literal

from pydantic import AwareDatetime, Field, model_validator

from .contracts import (
    Contract,
    Digest,
    ExactReference,
    ForgeError,
    Identifier,
    Producer,
    Scope,
    contract_digest,
)
from .records import Record


class WriteOperation(Contract):
    schema_version: Literal["forge.operation.v1"] = "forge.operation.v1"
    scope: Scope
    operation_id: Identifier
    record_id: Identifier
    expected_revision: int = Field(ge=0, le=2147483646, strict=True)
    producer: Producer
    payload: Record
    payload_digest_sha256: Digest

    def content_digest(self) -> str:
        return contract_digest(
            self.model_dump(mode="json", exclude={"payload_digest_sha256"})
        )

    @model_validator(mode="after")
    def digest_binding(self):
        if self.payload_digest_sha256 != self.content_digest():
            raise ValueError(
                "operation payload digest does not match the complete request"
            )
        return self


class Receipt(Contract):
    schema_version: Literal["forge.receipt.v1"] = "forge.receipt.v1"
    scope: Scope
    operation_id: Identifier
    payload_digest_sha256: Digest
    reference: ExactReference
    cursor: int = Field(ge=1)
    recorded_at: AwareDatetime


class Event(Contract):
    producer: Literal["forge"] = "forge"
    cursor: int = Field(ge=1)
    receipt: Receipt


class RecordRevision(Contract):
    scope: Scope
    reference: ExactReference
    payload: Record
    producer: Producer
    operation_id: Identifier
    recorded_at: AwareDatetime


REVISION_REFERENCE_V1 = "forge.revision-reference.v1"


class RevisionReference(Contract):
    """Exact identity of one complete retained revision, provenance included.

    See docs/decisions/0001. ``reference.digest_sha256`` keeps its payload-only
    meaning; ``document_digest_sha256`` binds producer, operation and time too.
    It proves the document Forge recorded, not external producer attestation.
    """

    schema_version: Literal["forge.revision-reference.v1"] = REVISION_REFERENCE_V1
    reference: ExactReference
    document_digest_sha256: Digest


def revision_reference(record: RecordRevision) -> RevisionReference:
    record = RecordRevision.model_validate(record.model_dump(mode="json"))
    if (
        record.reference.authority != "forge"
        or record.reference.kind != record.payload.kind
        or record.reference.digest_sha256 != contract_digest(record.payload)
    ):
        raise ForgeError("reference_conflict", "record differs from exact source bytes")
    return RevisionReference(
        reference=record.reference, document_digest_sha256=contract_digest(record)
    )


class PublicWrite(Contract):
    """Public intent; backend supplies authenticated producer and canonical scope."""

    operation_id: Identifier
    record_id: Identifier
    expected_revision: int = Field(ge=0, le=2147483646, strict=True)
    payload: Record
    request_digest_sha256: Digest

    @model_validator(mode="after")
    def request_binding(self):
        if self.request_digest_sha256 != contract_digest(
            self.model_dump(mode="json", exclude={"request_digest_sha256"})
        ):
            raise ValueError("public request digest does not match intent")
        return self
