# Generated by Forge scripts/export_contracts.py.
# Schema SHA256: e1ef9bd482d45c91eadccee902efe873c53b63a736a0f694a06223c95e37b8a9
"""Distinct scientific objects and exact citations. See docs/contracts.md.

Claims, reviews and measurements remain separate records. No record dispatches
work, approves spending, grants access or publishes a contribution.
"""

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, Field, JsonValue, model_validator

from .contracts import Contract, Digest, ExactReference, Identifier, Text
from .evaluation import EvaluationBinding
from .exports import ScientificExport, SourceNotice
from .resources import ResourceBinding, WorkspaceBinding

References = Annotated[tuple[ExactReference, ...], Field(max_length=1024)]


class Effort(Contract):
    kind: Literal["effort"] = "effort"
    objective: Text
    sources: References = ()


class Hypothesis(Contract):
    kind: Literal["hypothesis"] = "hypothesis"
    statement: Text
    prediction: Text
    decision_rule: Text
    analysis_plan: Text
    sources: References = ()


class Experiment(Contract):
    kind: Literal["experiment"] = "experiment"
    title: Text
    specification: Text
    hypothesis: ExactReference | None = None
    effort: ExactReference | None = None
    inputs: References = ()
    arms: tuple[Identifier, ...] = Field(default=(), max_length=128)
    sources: References = ()


class Trial(Contract):
    kind: Literal["trial"] = "trial"
    experiment: ExactReference
    arm: Identifier | None = None
    configuration: dict[str, JsonValue]
    executed_inputs: References
    execution: ExactReference | None = None
    state: Literal["registered", "running", "succeeded", "failed", "interrupted", "rejected"]
    sources: References = ()


class Measurement(Contract):
    name: Identifier
    value: float | None = Field(strict=True, allow_inf_nan=False)
    unit: Identifier
    uncertainty: float | None = Field(default=None, strict=True, ge=0, allow_inf_nan=False)


class Result(Contract):
    kind: Literal["result"] = "result"
    trial: ExactReference
    outcome: Literal[
        "measured",
        "failed",
        "negative",
        "null",
        "inconclusive",
        "interrupted",
        "rejected",
    ]
    measurements: tuple[Measurement, ...] = Field(default=(), max_length=256)
    evaluator: ExactReference | None = None
    verification: Literal["unverified", "producer_bound"] = "unverified"
    scorer_receipt: ExactReference | None = None
    evaluation: EvaluationBinding | None = None
    evidence: References = ()
    usage: References = ()
    missing_evidence: tuple[Text, ...] = Field(default=(), max_length=256)
    limitations: tuple[Text, ...] = Field(default=(), max_length=256)
    sources: References = ()

    @model_validator(mode="after")
    def measured_evidence(self):
        if self.evaluation and self.evaluator != self.evaluation.evaluator:
            raise ValueError("result evaluator differs from ingestion binding")
        if self.evaluation and self.scorer_receipt != self.evaluation.scorer_receipt:
            raise ValueError("scorer receipt differs from ingestion binding")
        if self.verification == "producer_bound" and self.scorer_receipt is None:
            raise ValueError("producer-bound grades require an exact scorer receipt")
        if self.outcome == "measured" and (
            not self.measurements or not self.evaluator or not self.evidence
        ):
            raise ValueError("measured results require measurements, evaluator and evidence")
        return self


class ResearchLog(Contract):
    kind: Literal["research_log"] = "research_log"
    title: Text
    effort: ExactReference | None = None
    sources: References = ()


class LogEntry(Contract):
    kind: Literal["log_entry"] = "log_entry"
    log: ExactReference
    category: Literal["observation", "rationale", "attempt", "failure", "decision", "correction"]
    text: Text
    occurred_at: AwareDatetime
    correction_of: ExactReference | None = None
    sources: References = ()

    @model_validator(mode="after")
    def correction_binding(self):
        if (self.category == "correction") != (self.correction_of is not None):
            raise ValueError("corrections require an exact prior entry")
        return self


class Report(Contract):
    kind: Literal["report"] = "report"
    title: Text
    body: Annotated[str, Field(min_length=1, max_length=262144)]
    methods: Text
    claims: tuple[Text, ...] = Field(default=(), max_length=256)
    limitations: tuple[Text, ...] = Field(default=(), max_length=256)
    sources: References = ()


class Review(Contract):
    kind: Literal["review"] = "review"
    target: ExactReference
    decision: Literal["comment", "approved", "rejected", "needs_correction"]
    rationale: Text
    sources: References = ()


class ArtifactDeliveryBinding(Contract):
    publication_id: UUID
    logical_path: Annotated[str, Field(min_length=1, max_length=1024)]

    @model_validator(mode="after")
    def normalized_path(self):
        if (
            "\\" in self.logical_path
            or "\x00" in self.logical_path
            or any(part in {"", ".", ".."} for part in self.logical_path.split("/"))
        ):
            raise ValueError("artifact logical path must be normalized and relative")
        return self


class Artifact(Contract):
    kind: Literal["artifact"] = "artifact"
    object: ExactReference
    manifest: ExactReference
    role: Literal["input", "intermediate", "output", "evidence"]
    media_type: Text
    byte_count: int = Field(ge=0)
    delivery: ArtifactDeliveryBinding | None = None
    sources: References = ()

    @model_validator(mode="after")
    def retained_custody(self):
        if self.delivery and (
            self.object.authority != "artifact-platform"
            or self.manifest.authority != "artifact-platform"
            or self.manifest.record_id != str(self.delivery.publication_id)
        ):
            raise ValueError("delivery must pin the exact Artifact Platform publication")
        if self.object.authority == "forge" or self.manifest.authority == "forge":
            raise ValueError("artifact custody belongs to the canonical artifact authority")
        return self


class Snapshot(Contract):
    kind: Literal["snapshot"] = "snapshot"
    cutoff_at: AwareDatetime
    sources: References = Field(min_length=1)
    archive: ExactReference
    capture_completeness: Literal["complete", "partial"]
    gaps: tuple[Text, ...] = Field(default=(), max_length=256)
    imported_log_head_sha256: Digest | None = None
    imported_log_count: int | None = Field(default=None, ge=0, le=5000)

    @model_validator(mode="after")
    def capture_binding(self):
        if (self.capture_completeness == "partial") != bool(self.gaps):
            raise ValueError("partial capture requires explicit gaps")
        if (self.imported_log_head_sha256 is None) != (self.imported_log_count is None):
            raise ValueError("imported log head and count must be supplied together")
        return self


Record = Annotated[
    Effort
    | Hypothesis
    | Experiment
    | Trial
    | Result
    | ResearchLog
    | LogEntry
    | Report
    | Review
    | Artifact
    | Snapshot
    | ScientificExport
    | SourceNotice
    | ResourceBinding
    | WorkspaceBinding,
    Field(discriminator="kind"),
]
