# Generated by Forge scripts/export_contracts.py.
# Schema SHA256: 08a0735563a42e3a45b5497b552bb2b1ff122a630c121e2eed28167896adf8d3
"""Scientific associations over retained resource and effect authorities.

See SYN-3549–3554. These bindings neither launch effects nor grant access;
resolved defaults, credentials, job control and settlement stay backend-owned.
"""

from typing import Literal

from pydantic import Field, model_validator

from .contracts import Contract, ExactReference, Text


class DatasetSplit(Contract):
    role: Literal["train", "dev", "heldout"]
    manifest: ExactReference
    ancestors: tuple[ExactReference, ...] = Field(default=(), max_length=128)


class ResourceBinding(Contract):
    kind: Literal["resource_binding"] = "resource_binding"
    category: Literal[
        "file",
        "dataset",
        "data_pool",
        "model",
        "checkpoint",
        "evaluator",
        "repository",
        "workspace",
        "image",
        "deployment",
        "pool",
        "optimizer_job",
    ]
    title: Text
    resource: ExactReference
    manifest: ExactReference
    admission: ExactReference | None = None
    usage: tuple[ExactReference, ...] = Field(default=(), max_length=128)
    splits: tuple[DatasetSplit, ...] = Field(default=(), max_length=3)
    execution: ExactReference | None = None
    sources: tuple[ExactReference, ...] = Field(default=(), max_length=1024)

    @model_validator(mode="after")
    def retained_authority(self):
        if self.resource.authority == "forge" or self.manifest.authority == "forge":
            raise ValueError("resource and manifest retain existing custody")
        if self.splits and self.category != "dataset":
            raise ValueError("split manifests belong to dataset bindings")
        if len({split.role for split in self.splits}) != len(self.splits):
            raise ValueError("dataset split roles must be unique")
        return self


class WorkspaceBinding(Contract):
    kind: Literal["workspace_binding"] = "workspace_binding"
    repository: ExactReference
    commit: ExactReference
    archive: ExactReference
    image: ExactReference
    workspace: ExactReference
    execution: ExactReference | None = None
    sources: tuple[ExactReference, ...] = Field(default=(), max_length=1024)

    @model_validator(mode="after")
    def exact_checkout(self):
        if self.commit.authority != self.repository.authority:
            raise ValueError("repository and commit require the same Git authority")
        if any(
            reference.authority == "forge"
            for reference in (
                self.repository,
                self.commit,
                self.archive,
                self.image,
                self.workspace,
            )
        ):
            raise ValueError("workspace effects retain existing custody")
        return self
