# Verilog Eval Config for Groq Qwen3-32B
# Quick eval to test the Verilog task app before RL training

[eval]
app_id = "grpo-verilog"
task_app_url = "https://synth-laboratories--grpo-verilog-task-app-fastapi-app-dev.modal.run"
model = "groq:qwen3-32b"
seeds = [0, 1, 2]
max_turns = 15
concurrency = 1
return_trace = true
trace_format = "structured"

[eval.env_config]
difficulty = "medium"

[eval.policy_config]
provider = "groq"
model = "qwen/qwen3-32b"
temperature = 0.2
max_tokens = 768
inference_url = "https://api.groq.com/openai/v1/chat/completions"
