"""Concise public types for ``SynthClient().research``.

The hero workflow is ``Project -> Swarm -> events/result``.  Factory is the
durable optimization loop that creates and evaluates Efforts.  Names prefixed
with ``Research`` remain lazily importable through the 0.17 compatibility line
but are intentionally absent from public discovery.
"""

from __future__ import annotations

import importlib

from synth_ai.core.research.contracts import (
    ActivityActor,
    ActivityActorState,
    ActivityCursor,
    ActivityEvent,
    ActivityEventId,
    ActivityMessage,
    ActivityRun,
    ActivityTask,
    ActivityTaskState,
    ActivityWindow,
    ActivityWindowReceipt,
    ActivityWorkProduct,
    ActorId,
    ActorRuntimeImageMaterialization,
    ActorRuntimeImageRelease,
    ActorRuntimeImageReleaseArchive,
    ActorRuntimeImageReleaseDeclaration,
    ActorRuntimeImageReleaseList,
    ArtifactId,
    ActorTokenUsage,
    ActorUsage,
    ActorUsageMoney,
    ActorHarness,
    ActorModel,
    BudgetPolicy,
    CapacityPolicy,
    ContentDisposition,
    ConfigurationVersionId,
    Effort,
    EffortId,
    EffortPatch,
    EffortRecurrence,
    EffortSpec,
    ENVIRONMENT_SCHEMA_VERSION,
    Environment,
    EnvironmentDetail,
    EnvironmentDigest,
    EnvironmentId,
    EnvironmentIsolationSpec,
    EnvironmentJsonObject,
    EnvironmentKind,
    EnvironmentManifest,
    EnvironmentMountSpec,
    EnvironmentName,
    EnvironmentPreflight,
    EnvironmentPreflightError,
    EnvironmentPreflightResult,
    EnvironmentPreflightSpec,
    EnvironmentRepositorySpec,
    EnvironmentResponsibleParty,
    EnvironmentSecretSpec,
    EvidenceArtifact,
    EvidenceFreshness,
    EvidenceWorkProduct,
    Factory,
    FactoryId,
    FactoryPatch,
    FactorySpec,
    FactoryTransition,
    ExecutionProfile,
    HostKind,
    LocalExecution,
    CraftaxScorerImageRelease,
    CraftaxScorerImageReleaseDeclaration,
    ImageRelease,
    ImageReleaseDeclaration,
    ImageReleaseFinalize,
    ImageReleaseFinalizeRequest,
    ImageReleaseFinalizeResponse,
    ImageReleaseId,
    ImageReleaseKind,
    ImageReleaseStagingCleanup,
    ImageReleaseUpload,
    ImageReleaseUploadRequest,
    ImageReleaseUploadResponse,
    ImageUploadId,
    MessageId,
    ParticipantSessionId,
    Project,
    ProjectDataset,
    ProjectDatasetEncoding,
    ProjectDatasetId,
    ProjectDatasetSourceKind,
    ProjectDatasetUpload,
    ProjectEventId,
    ProjectId,
    ProjectPatch,
    ProjectSpec,
    ProjectRepository,
    ProjectRepositoryDeletion,
    ProjectRepositoryId,
    ProjectRepositoryPatch,
    ProjectRepositoryRole,
    ProjectRepositoryScope,
    ProjectRepositorySpec,
    ProjectWorkspaceInputs,
    ResourceMetadata,
    RuntimeImageKind,
    RuntimeImageRef,
    ResolvedSwarmConfiguration,
    Swarm,
    SwarmActivity,
    SwarmEvidence,
    SwarmHeartbeat,
    BranchSpec,
    BranchResult as Branch,
    ActorHarness,
    ActorImageBinding,
    ActorModel,
    KickoffArtifact,
    PlatformResolvedExecutionTarget,
    RoleBinding,
    RoleBindings,
    SwarmSpec,
    SwarmPreflight as Preflight,
    SwarmState,
    SwarmLivenessPhase,
    SwarmRuntimeSnapshot,
    SwarmTranscriptEvent,
    SwarmTranscriptPage,
    SwarmUsage,
    WorkMode,
    WorkerRolePalette,
    TokenCounts,
    TaskId,
    TokenUsage,
    TranscriptCursor,
    TranscriptCursorKind,
    TranscriptEventId,
    TranscriptFreshness,
    TranscriptParticipant,
    TranscriptPayloadClassification,
    TranscriptProjectionAuthority,
    TranscriptRedactionProfile,
    TranscriptReplayMode,
    TranscriptView,
    TranscriptVisibilityDecision,
    UsageFreshness,
    UsageMoney,
    UsageSource,
    UserId,
    WORKSPACE_BATCH_UPLOAD_FILE_LIMIT,
    WORKSPACE_UPLOAD_FILE_LIMIT,
    WorkspaceFileEncoding,
    WorkspaceFileId,
    WorkspaceFileKind,
    WorkspaceFileScope,
    WorkspaceFilesBatchUploadProgress,
    WorkspaceFilesBatchUploadReceipt,
    WorkspaceFilesBatchUploadRequest,
    WorkspaceFilesUploadReceipt,
    WorkspaceFilesUploadRequest,
    WorkspaceFileUpload,
    WorkspaceFileVisibility,
    WorkspaceInputState,
    WorkspaceMetadata,
    WorkspaceProjectRepository,
    WorkspaceRepositoryAuthMode,
    WorkspaceRepositoryBootstrapMode,
    WorkspaceSourceRepository,
    WorkspaceSourceRepositoryKind,
    WorkspaceSourceRepositoryReceipt,
    WorkspaceSourceRepositorySpec,
    WorkspaceStoredFile,
    ResourceLimit as Limit,
    RuntimeKind,
    RuntimeImageReleaseArchiveResponse,
    RuntimeImageReleaseId,
    RuntimeImageReleaseListResponse,
    RuntimeImageReleaseStatus,
    SwarmId,
    WorkMode,
    WorkProductArtifactLink,
    WorkProductArtifactRole,
    WorkProductBlocker,
    WorkProductId,
    WorkProductKind,
    WorkProductReadiness,
    WorkProductStatus,
)
from synth_ai.core.research.project_workspaces import WorkspaceBatchUploadError
from synth_ai.core.research.swarms import SwarmHandle
from synth_ai.core.errors import (
    RetryDirective as Retry,
    SynthError as Error,
    SynthErrorCategory as ErrorCategory,
    SynthErrorCode as ErrorCode,
    SynthFailure as Failure,
)
from synth_ai.core.research.events import (
    SwarmEvent,
    SwarmEventKind,
)
from synth_ai.research.async_client import AsyncClient
from synth_ai.research.client import Client

__all__ = [
    "ActivityActor",
    "ActivityActorState",
    "ActivityCursor",
    "ActivityEvent",
    "ActivityEventId",
    "ActivityMessage",
    "ActivityRun",
    "ActivityTask",
    "ActivityTaskState",
    "ActivityWindow",
    "ActivityWindowReceipt",
    "ActivityWorkProduct",
    "ActorId",
    "ActorRuntimeImageMaterialization",
    "ActorRuntimeImageRelease",
    "ActorRuntimeImageReleaseArchive",
    "ActorRuntimeImageReleaseDeclaration",
    "ActorRuntimeImageReleaseList",
    "ArtifactId",
    "ActorHarness",
    "ActorModel",
    "ActorTokenUsage",
    "ActorUsage",
    "ActorUsageMoney",
    "AsyncClient",
    "Branch",
    "BranchSpec",
    "BudgetPolicy",
    "CapacityPolicy",
    "Client",
    "ContentDisposition",
    "ConfigurationVersionId",
    "Effort",
    "EffortId",
    "EffortPatch",
    "EffortRecurrence",
    "EffortSpec",
    "ENVIRONMENT_SCHEMA_VERSION",
    "Environment",
    "EnvironmentDetail",
    "EnvironmentDigest",
    "EnvironmentId",
    "EnvironmentIsolationSpec",
    "EnvironmentJsonObject",
    "EnvironmentKind",
    "EnvironmentManifest",
    "EnvironmentMountSpec",
    "EnvironmentName",
    "EnvironmentPreflight",
    "EnvironmentPreflightError",
    "EnvironmentPreflightResult",
    "EnvironmentPreflightSpec",
    "EnvironmentRepositorySpec",
    "EnvironmentResponsibleParty",
    "EnvironmentSecretSpec",
    "EvidenceArtifact",
    "EvidenceFreshness",
    "EvidenceWorkProduct",
    "Error",
    "ErrorCategory",
    "ErrorCode",
    "Failure",
    "Factory",
    "FactoryId",
    "FactoryPatch",
    "FactorySpec",
    "FactoryTransition",
    "ExecutionProfile",
    "HostKind",
    "LocalExecution",
    "ActorHarness",
    "ActorImageBinding",
    "ActorModel",
    "KickoffArtifact",
    "PlatformResolvedExecutionTarget",
    "RoleBinding",
    "RoleBindings",
    "WorkerRolePalette",
    "WorkMode",
    "CraftaxScorerImageRelease",
    "CraftaxScorerImageReleaseDeclaration",
    "ImageRelease",
    "ImageReleaseDeclaration",
    "ImageReleaseFinalize",
    "ImageReleaseFinalizeRequest",
    "ImageReleaseFinalizeResponse",
    "ImageReleaseId",
    "ImageReleaseKind",
    "ImageReleaseStagingCleanup",
    "ImageReleaseUpload",
    "ImageReleaseUploadRequest",
    "ImageReleaseUploadResponse",
    "ImageUploadId",
    "Limit",
    "MessageId",
    "ParticipantSessionId",
    "Preflight",
    "Project",
    "ProjectDataset",
    "ProjectDatasetEncoding",
    "ProjectDatasetId",
    "ProjectDatasetSourceKind",
    "ProjectDatasetUpload",
    "ProjectEventId",
    "ProjectId",
    "ProjectPatch",
    "ProjectSpec",
    "ProjectRepository",
    "ProjectRepositoryDeletion",
    "ProjectRepositoryId",
    "ProjectRepositoryPatch",
    "ProjectRepositoryRole",
    "ProjectRepositoryScope",
    "ProjectRepositorySpec",
    "ProjectWorkspaceInputs",
    "ResolvedSwarmConfiguration",
    "RuntimeKind",
    "RuntimeImageReleaseArchiveResponse",
    "RuntimeImageReleaseId",
    "RuntimeImageReleaseListResponse",
    "RuntimeImageReleaseStatus",
    "RuntimeImageKind",
    "RuntimeImageRef",
    "Retry",
    "ResourceMetadata",
    "Swarm",
    "SwarmActivity",
    "SwarmEvidence",
    "SwarmEvent",
    "SwarmEventKind",
    "SwarmHeartbeat",
    "SwarmHandle",
    "SwarmId",
    "SwarmLivenessPhase",
    "SwarmRuntimeSnapshot",
    "SwarmSpec",
    "SwarmState",
    "SwarmTranscriptEvent",
    "SwarmTranscriptPage",
    "SwarmUsage",
    "TaskId",
    "TokenCounts",
    "TokenUsage",
    "TranscriptCursor",
    "TranscriptCursorKind",
    "TranscriptEventId",
    "TranscriptFreshness",
    "TranscriptParticipant",
    "TranscriptPayloadClassification",
    "TranscriptProjectionAuthority",
    "TranscriptRedactionProfile",
    "TranscriptReplayMode",
    "TranscriptView",
    "TranscriptVisibilityDecision",
    "UsageFreshness",
    "UsageMoney",
    "UsageSource",
    "UserId",
    "WORKSPACE_BATCH_UPLOAD_FILE_LIMIT",
    "WORKSPACE_UPLOAD_FILE_LIMIT",
    "WorkspaceBatchUploadError",
    "WorkspaceFileEncoding",
    "WorkspaceFileId",
    "WorkspaceFileKind",
    "WorkspaceFileScope",
    "WorkspaceFilesBatchUploadProgress",
    "WorkspaceFilesBatchUploadReceipt",
    "WorkspaceFilesBatchUploadRequest",
    "WorkspaceFilesUploadReceipt",
    "WorkspaceFilesUploadRequest",
    "WorkspaceFileUpload",
    "WorkspaceFileVisibility",
    "WorkspaceInputState",
    "WorkspaceMetadata",
    "WorkspaceProjectRepository",
    "WorkspaceRepositoryAuthMode",
    "WorkspaceRepositoryBootstrapMode",
    "WorkspaceSourceRepository",
    "WorkspaceSourceRepositoryKind",
    "WorkspaceSourceRepositoryReceipt",
    "WorkspaceSourceRepositorySpec",
    "WorkspaceStoredFile",
    "WorkMode",
    "WorkProductArtifactLink",
    "WorkProductArtifactRole",
    "WorkProductBlocker",
    "WorkProductId",
    "WorkProductKind",
    "WorkProductReadiness",
    "WorkProductStatus",
]

_COMPATIBILITY_EXPORTS: dict[str, tuple[str, str]] = {
    "AsyncResearchClient": ("synth_ai.research.async_client", "AsyncResearchClient"),
    "ResearchApiError": ("synth_ai.research.errors", "ResearchApiError"),
    "ResearchArtifact": ("synth_ai.research.models", "ResearchArtifact"),
    "ResearchArtifactManifest": ("synth_ai.research.models", "ResearchArtifactManifest"),
    "ResearchAgentHarness": ("synth_ai.core.research.contracts", "ActorHarness"),
    "ResearchAgentModel": ("synth_ai.core.research.contracts", "ActorModel"),
    "ResearchAgentProfileBindings": (
        "synth_ai.research.models",
        "ResearchAgentProfileBindings",
    ),
    "ResearchAuthorityReadouts": (
        "synth_ai.research.models",
        "ResearchAuthorityReadouts",
    ),
    "ResearchBillingCatalog": ("synth_ai.research.models", "ResearchBillingCatalog"),
    "ResearchBillingDrawdown": ("synth_ai.research.models", "ResearchBillingDrawdown"),
    "ResearchBillingEntitlements": (
        "synth_ai.research.models",
        "ResearchBillingEntitlements",
    ),
    "ResearchBillingPlan": ("synth_ai.research.models", "ResearchBillingPlan"),
    "ResearchClient": ("synth_ai.research.client", "ResearchClient"),
    "ResearchConcurrentRunLimitExceededError": (
        "synth_ai.research.errors",
        "ResearchConcurrentRunLimitExceededError",
    ),
    "ResearchEconomicsAPI": ("synth_ai.research.economics", "ResearchEconomicsAPI"),
    "ResearchEnvironmentKind": ("synth_ai.core.research.contracts", "EnvironmentKind"),
    "ResearchFactoriesAPI": ("synth_ai.research.factories", "ResearchFactoriesAPI"),
    "ResearchHostKind": ("synth_ai.core.research.contracts", "HostKind"),
    "ResearchInsufficientCreditsError": (
        "synth_ai.research.errors",
        "ResearchInsufficientCreditsError",
    ),
    "ResearchLimitExceededError": (
        "synth_ai.research.errors",
        "ResearchLimitExceededError",
    ),
    "ResearchLimitsAPI": ("synth_ai.research.limits", "ResearchLimitsAPI"),
    "ResearchOrgLimits": ("synth_ai.research.models", "ResearchOrgLimits"),
    "ResearchProject": ("synth_ai.core.research.contracts", "ResearchProject"),
    "ResearchProjectCreateRequest": (
        "synth_ai.core.research.contracts",
        "ResearchProjectCreateRequest",
    ),
    "ResearchProjectPatchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchProjectPatchRequest",
    ),
    "ResearchProjectEconomics": (
        "synth_ai.research.models",
        "ResearchProjectEconomics",
    ),
    "ResearchProjectMonthlyBudgetExhaustedError": (
        "synth_ai.research.errors",
        "ResearchProjectMonthlyBudgetExhaustedError",
    ),
    "ResearchProjectsAPI": ("synth_ai.core.research.projects", "ResearchProjectsAPI"),
    "ResearchRoleBinding": ("synth_ai.research.models", "ResearchRoleBinding"),
    "ResearchRoleBindings": ("synth_ai.research.models", "ResearchRoleBindings"),
    "ResearchRun": ("synth_ai.research.models", "ResearchRun"),
    "ResearchRunHandle": ("synth_ai.research.runs", "ResearchRunHandle"),
    "ResearchRunLaunchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchRunLaunchRequest",
    ),
    "ResearchRunProgress": ("synth_ai.research.models", "ResearchRunProgress"),
    "ResearchRunSession": ("synth_ai.research.runs", "ResearchRunSession"),
    "ResearchRunbookPreset": ("synth_ai.research.models", "ResearchRunbookPreset"),
    "ResearchRunnableProjectRequest": (
        "synth_ai.core.research.contracts",
        "ResearchProjectCreateRequest",
    ),
    "ResearchRunsAPI": ("synth_ai.research.runs", "ResearchRunsAPI"),
    "ResearchRuntimeKind": ("synth_ai.core.research.contracts", "RuntimeKind"),
    "ResearchSecretsAPI": ("synth_ai.research.secrets", "ResearchSecretsAPI"),
    "ResearchStructuredDenialError": (
        "synth_ai.research.errors",
        "ResearchStructuredDenialError",
    ),
    "ResearchSwarm": ("synth_ai.core.research.contracts", "ResearchSwarm"),
    "ResearchSwarmBranchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmBranchRequest",
    ),
    "ResearchSwarmBranchResult": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmBranchResult",
    ),
    "ResearchSwarmHandle": ("synth_ai.core.research.swarms", "ResearchSwarmHandle"),
    "ResearchSwarmLaunchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmLaunchRequest",
    ),
    "ResearchSwarmPreflight": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmPreflight",
    ),
    "ResearchSwarmState": ("synth_ai.core.research.contracts", "ResearchSwarmState"),
    "ResearchSwarmsAPI": ("synth_ai.core.research.swarms", "ResearchSwarmsAPI"),
    "ResearchTagSessionCreateRequest": (
        "synth_ai.research.models",
        "ResearchTagSessionCreateRequest",
    ),
    "ResearchWorkMode": ("synth_ai.core.research.contracts", "WorkMode"),
    "ResearchWorkerRolePalette": (
        "synth_ai.research.models",
        "ResearchWorkerRolePalette",
    ),
    "ResearchWorkProduct": ("synth_ai.research.models", "ResearchWorkProduct"),
    "ResourceLimit": ("synth_ai.core.research.contracts", "ResourceLimit"),
}


def __getattr__(name: str) -> object:
    target = _COMPATIBILITY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attribute = target
    value = getattr(importlib.import_module(module_name), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
