"""Compatibility re-export; implementation lives in contracts.smr_actor_models."""

from synth_ai.core.research.contracts.smr_actor_models import (
    SMR_ACTOR_MODEL_POLICY,
    SMR_ACTOR_SUBTYPE_VALUES,
    SMR_ACTOR_SUBTYPE_VALUES_BY_TYPE,
    SMR_ACTOR_TYPE_VALUES,
    SMR_ORCHESTRATOR_SUBTYPE_VALUES,
    SMR_REVIEWER_SUBTYPE_VALUES,
    SMR_SHARED_TOP_LEVEL_AGENT_MODEL_VALUES,
    SMR_WORKER_SUBTYPE_VALUES,
    SmrActorModelAssignment,
    SmrActorSubtype,
    SmrActorType,
    SmrOrchestratorSubtype,
    SmrReviewerSubtype,
    SmrWorkerSubtype,
    coerce_smr_actor_model_assignment,
    coerce_smr_actor_subtype,
    coerce_smr_actor_type,
    normalize_actor_model_assignments,
    validate_shared_top_level_agent_model,
)

__all__ = [
    'SMR_ACTOR_MODEL_POLICY',
    'SMR_ACTOR_SUBTYPE_VALUES',
    'SMR_ACTOR_SUBTYPE_VALUES_BY_TYPE',
    'SMR_ACTOR_TYPE_VALUES',
    'SMR_ORCHESTRATOR_SUBTYPE_VALUES',
    'SMR_REVIEWER_SUBTYPE_VALUES',
    'SMR_SHARED_TOP_LEVEL_AGENT_MODEL_VALUES',
    'SMR_WORKER_SUBTYPE_VALUES',
    'SmrActorModelAssignment',
    'SmrActorSubtype',
    'SmrActorType',
    'SmrOrchestratorSubtype',
    'SmrReviewerSubtype',
    'SmrWorkerSubtype',
    'coerce_smr_actor_model_assignment',
    'coerce_smr_actor_subtype',
    'coerce_smr_actor_type',
    'normalize_actor_model_assignments',
    'validate_shared_top_level_agent_model',
]
