"""Public Research types for ``SynthClient().research``.

The hero workflow is ``Project -> Swarm -> events/result``.  Factory is the
durable optimization loop that creates and evaluates Efforts.  Names prefixed with
``Research`` are the canonical domain vocabulary.
"""

from __future__ import annotations

import importlib

from synth_ai.core.errors import (
    RetryDirective as Retry,
)
from synth_ai.core.errors import (
    SynthError as Error,
)
from synth_ai.core.errors import (
    SynthErrorCategory as ErrorCategory,
)
from synth_ai.core.errors import (
    SynthErrorCode as ErrorCode,
)
from synth_ai.core.errors import (
    SynthFailure as Failure,
)
from synth_ai.core.research.client import AsyncClient
from synth_ai.core.research.contracts import (
    ENVIRONMENT_SCHEMA_VERSION,
    WORKSPACE_BATCH_UPLOAD_FILE_LIMIT,
    WORKSPACE_UPLOAD_FILE_LIMIT,
    ActivityActor,
    ActivityActorState,
    ActivityCursor,
    ActivityEvent,
    ActivityEventId,
    ActivityMessage,
    ActivityRun,
    ActivityTask,
    ActivityTaskState,
    ActivityWindow,
    ActivityWindowReceipt,
    ActivityWorkProduct,
    ActorHarness,
    ActorId,
    ActorImageBinding,
    ActorModel,
    ActorRuntimeImageMaterialization,
    ActorRuntimeImageRelease,
    ActorRuntimeImageReleaseArchive,
    ActorRuntimeImageReleaseDeclaration,
    ActorRuntimeImageReleaseList,
    ActorTokenUsage,
    ActorUsage,
    ActorUsageMoney,
    ArtifactId,
    BoundRuntimeExecutionTarget,
    BranchSpec,
    BudgetPolicy,
    CapacityPolicy,
    ConfigurationVersionId,
    ContentDisposition,
    DataBindingCreateRequest,
    DataBindingResponse,
    DatasetRevisionFinalizeRequest,
    DatasetRevisionFinalizeResponse,
    DatasetRevisionLifecycleRequest,
    DatasetRevisionPreparationResponse,
    DatasetRevisionPrepareRequest,
    DatasetRevisionCreateRequest,
    DatasetRevisionResponse,
    Delivery,
    DeliveryReceipt,
    DraftDeliveryAuthorityResponse,
    EnsureDraftDeliveryRequest,
    CraftaxScorerImageRelease,
    CraftaxScorerImageReleaseDeclaration,
    CredentialProvider,
    DirectedEffortOutcomeSpec,
    Effort,
    EffortBudgetPolicy,
    EffortId,
    EffortPatch,
    EffortRecurrence,
    EffortMaintenanceRecurrencePolicy,
    EffortResearchRecurrencePolicy,
    EffortRunClass,
    EffortSpec,
    EffortType,
    Environment,
    EnvironmentDetail,
    EnvironmentDigest,
    EnvironmentId,
    EnvironmentIsolationSpec,
    EnvironmentJsonObject,
    EnvironmentKind,
    EnvironmentManifest,
    EnvironmentMountSpec,
    EnvironmentName,
    EnvironmentPreflight,
    EnvironmentPreflightError,
    EnvironmentPreflightResult,
    EnvironmentPreflightSpec,
    EnvironmentRepositorySpec,
    EnvironmentResponsibleParty,
    EnvironmentSecretSpec,
    EnvironmentVariable,
    EvidenceArtifact,
    EvidenceFreshness,
    EvidenceWorkProduct,
    ExecutionCapability,
    ExecutionProfile,
    Factory,
    FactoryBudgetPeriod,
    FactoryBudgetPolicy,
    FactoryId,
    FactoryKind,
    FactoryLunaRole,
    FactoryPatch,
    FactoryResultAuthorityGeneration,
    FactoryRoleReceiptMintRequest,
    FactoryRoleReceiptProvenance,
    FactoryRoleReceiptResponse,
    FactoryRoleReceiptRuntimeEvidence,
    FactorySpec,
    FactoryTransition,
    FundingSource,
    HostKind,
    ImageRelease,
    ImageReleaseDeclaration,
    ImageReleaseFinalize,
    ImageReleaseFinalizeRequest,
    ImageReleaseFinalizeResponse,
    ImageReleaseId,
    ImageReleaseKind,
    ImageReleaseStorageIdentity,
    ImageReleaseUpload,
    ImageReleaseUploadReconciliation,
    ImageReleaseUploadRequest,
    ImageReleaseUploadResponse,
    ImageUploadId,
    InferenceProvider,
    KickoffArtifact,
    KickoffMessage,
    KickoffMessageMode,
    LocalExecution,
    MAGI_CANONICAL_USER_BY_MODE,
    MagiCanonicalUser,
    MagiDecisionKind,
    MagiDecisionReceiptResponse,
    MagiDecisionRequest,
    MagiMode,
    MessageId,
    OpenEndedQuestionSpec,
    ParticipantSessionId,
    PlatformResolvedExecutionTarget,
    PrimaryParentKind,
    PrimaryParentRef,
    Project,
    ProjectComputerCleanupReceiptResponse,
    ProjectComputerCleanupRequest,
    ProjectComputerExecuteRequest,
    ProjectComputerInspectRequest,
    ProjectComputerLeaseAcquireRequest,
    ProjectComputerLeaseReleaseRequest,
    ProjectComputerLeaseRenewRequest,
    ProjectComputerLeaseResponse,
    ProjectComputerLifecycle,
    ProjectComputerOperationReconcileRequest,
    ProjectComputerProvisionRequest,
    ProjectComputerProvisionReceipt,
    ProjectComputerReplaceRequest,
    ProjectComputerResponse,
    ProjectComputerRestorationReceipt,
    ProjectComputerRetirementReceipt,
    ProjectComputerWorkspaceSnapshot,
    ProjectRuntimeOperationReceipt,
    FactoryStorageAuthorityResponse,
    ProjectDataset,
    ProjectDatasetEncoding,
    ProjectDatasetId,
    ProjectDatasetSourceKind,
    ProjectDatasetUpload,
    ProjectEventId,
    ProjectId,
    ProjectPatch,
    ProjectRepository,
    ProjectRepositoryDeletion,
    ProjectRepositoryId,
    ProjectRepositoryPatch,
    ProjectRepositoryRole,
    ProjectRepositoryScope,
    ProjectRepositorySpec,
    ProjectSpec,
    ProjectWorkspaceInputs,
    ProviderBinding,
    ProviderPolicy,
    ResolvedSwarmConfiguration,
    ResourceMetadata,
    ResourceProvider,
    ResourceRoutingPolicy,
    ResearchInternFactoryMembershipResponse,
    ResearchInternPatchRequest,
    ResearchInternPolicySet,
    ResearchInternProvisionRequest,
    ResearchInternResponse,
    ResearchInternStatus,
    RoleBinding,
    RoleBindings,
    Runbook,
    RunPolicy,
    RunPolicyAccess,
    RunPolicyLimits,
    RuntimeImageKind,
    RuntimeImageRef,
    RuntimeImageReleaseArchiveResponse,
    RuntimeImageReleaseId,
    RuntimeImageReleaseListResponse,
    RuntimeImageReleaseStatus,
    RuntimeKind,
    Swarm,
    SwarmActivity,
    SwarmEnvironment,
    SwarmEvidence,
    SwarmHeartbeat,
    SwarmId,
    SwarmLivenessPhase,
    SwarmRuntimeSnapshot,
    SwarmSpec,
    SwarmState,
    SwarmTranscriptEvent,
    SwarmTranscriptPage,
    SwarmUsage,
    TaskId,
    TokenCounts,
    TokenUsage,
    TraceBundleDownload,
    TraceBundleDownloadObject,
    TraceBundleObjectDeclaration,
    TraceBundleObjectKind,
    TraceBundlePrepareRequest,
    TraceBundlePublication,
    TraceBundlePublicationLineage,
    TraceBundlePublicationStatus,
    TraceBundleSourceArtifactRef,
    TraceCatalogProvider,
    TraceDownload,
    TraceEvidenceAuthorityRef,
    TraceExperimentRevisionRef,
    TraceObjectUpload,
    TracePromotionReceipt,
    TraceQueryResult,
    TraceRecordSummary,
    TraceStoreAccessReceipt,
    TraceStoreDescriptor,
    TraceStoreLifecycleReceipt,
    TraceStoreProvisionResult,
    TraceStoreProvisioningStatus,
    ToolProvider,
    TranscriptCursor,
    TranscriptCursorKind,
    TranscriptEventId,
    TranscriptFreshness,
    TranscriptParticipant,
    TranscriptPayloadClassification,
    TranscriptProjectionAuthority,
    TranscriptRedactionProfile,
    TranscriptReplayMode,
    TranscriptView,
    TranscriptVisibilityDecision,
    UsageFreshness,
    UsageMoney,
    UsageSource,
    UserId,
    ResearchVisual,
    ResearchVisualPage,
    ResearchVisualPatchRequest,
    ResearchVisualPromotionRequest,
    ResearchVisualVersions,
    Visual,
    VisualBlobState,
    VisualEvidencePayload,
    VisualPage,
    VisualPatch,
    VisualPromotion,
    VisualStatus,
    VisualVisibility,
    VisualVersions,
    WorkerRolePalette,
    WorkMode,
    WorkProductArtifactLink,
    WorkProductArtifactRole,
    WorkProductBlocker,
    WorkProductId,
    WorkProductKind,
    WorkProductReadiness,
    WorkProductStatus,
    WorkspaceFileEncoding,
    WorkspaceFileId,
    WorkspaceFileKind,
    WorkspaceFilesBatchUploadProgress,
    WorkspaceFilesBatchUploadReceipt,
    WorkspaceFilesBatchUploadRequest,
    WorkspaceFileScope,
    WorkspaceFilesUploadReceipt,
    WorkspaceFilesUploadRequest,
    WorkspaceFileUpload,
    WorkspaceFileVisibility,
    WorkspaceInputState,
    WorkspaceMetadata,
    WorkspaceProjectRepository,
    WorkspaceRepositoryAuthMode,
    WorkspaceRepositoryBootstrapMode,
    WorkspaceSourceRepository,
    WorkspaceSourceRepositoryKind,
    WorkspaceSourceRepositoryReceipt,
    WorkspaceSourceRepositorySpec,
    WorkspaceStoredFile,
    WorkspacePushConfirmationReceipt,
)
from synth_ai.core.research.contracts import (
    BranchResult as Branch,
)
from synth_ai.core.research.contracts import (
    ResourceLimit as Limit,
)
from synth_ai.core.research.contracts import (
    SwarmPreflight as Preflight,
)
from synth_ai.core.research.events import (
    SwarmEvent,
    SwarmEventKind,
)
from synth_ai.core.research.facade import Client
from synth_ai.core.research.project_workspaces import WorkspaceBatchUploadError
from synth_ai.core.research.project_deliveries import (
    AsyncProjectDeliveriesAPI,
    ProjectDeliveriesAPI,
)
from synth_ai.core.research.factory_storage import (
    AsyncFactoryStorageAPI,
    FactoryStorageAPI,
)
from synth_ai.core.research.swarms import SwarmHandle
from synth_ai.core.research.traces import FactoryTraceStoreAPI, ResearchTracesAPI
from synth_ai.core.research.visuals import AsyncVisualsAPI, VisualsAPI
from synth_ai.core.research.research_intern import (
    AsyncProjectComputerAPI,
    AsyncProjectDataBindingsAPI,
    AsyncResearchInternAPI,
    ProjectComputerAPI,
    ProjectDataBindingsAPI,
    ResearchInternAPI,
)

__all__ = [
    "AsyncProjectComputerAPI",
    "AsyncProjectDataBindingsAPI",
    "AsyncProjectDeliveriesAPI",
    "AsyncFactoryStorageAPI",
    "AsyncResearchInternAPI",
    "DataBindingCreateRequest",
    "DataBindingResponse",
    "DatasetRevisionCreateRequest",
    "DatasetRevisionFinalizeRequest",
    "DatasetRevisionFinalizeResponse",
    "DatasetRevisionLifecycleRequest",
    "DatasetRevisionPreparationResponse",
    "DatasetRevisionPrepareRequest",
    "DatasetRevisionResponse",
    "Delivery",
    "DeliveryReceipt",
    "DraftDeliveryAuthorityResponse",
    "EnsureDraftDeliveryRequest",
    "FactoryStorageAPI",
    "FactoryStorageAuthorityResponse",
    "MAGI_CANONICAL_USER_BY_MODE",
    "MagiCanonicalUser",
    "MagiDecisionKind",
    "MagiDecisionReceiptResponse",
    "MagiDecisionRequest",
    "MagiMode",
    "ActivityActor",
    "ActivityActorState",
    "ActivityCursor",
    "ActivityEvent",
    "ActivityEventId",
    "ActivityMessage",
    "ActivityRun",
    "ActivityTask",
    "ActivityTaskState",
    "ActivityWindow",
    "ActivityWindowReceipt",
    "ActivityWorkProduct",
    "ActorId",
    "ActorRuntimeImageMaterialization",
    "ActorRuntimeImageRelease",
    "ActorRuntimeImageReleaseArchive",
    "ActorRuntimeImageReleaseDeclaration",
    "ActorRuntimeImageReleaseList",
    "ArtifactId",
    "ActorHarness",
    "ActorModel",
    "ActorTokenUsage",
    "ActorUsage",
    "ActorUsageMoney",
    "AsyncClient",
    "AsyncVisualsAPI",
    "Branch",
    "BranchSpec",
    "BoundRuntimeExecutionTarget",
    "BudgetPolicy",
    "CapacityPolicy",
    "Client",
    "ContentDisposition",
    "CredentialProvider",
    "ConfigurationVersionId",
    "DirectedEffortOutcomeSpec",
    "Effort",
    "EffortBudgetPolicy",
    "EffortId",
    "EffortPatch",
    "EffortMaintenanceRecurrencePolicy",
    "EffortRecurrence",
    "EffortResearchRecurrencePolicy",
    "EffortRunClass",
    "EffortSpec",
    "EffortType",
    "ENVIRONMENT_SCHEMA_VERSION",
    "Environment",
    "EnvironmentDetail",
    "EnvironmentDigest",
    "EnvironmentId",
    "EnvironmentIsolationSpec",
    "EnvironmentJsonObject",
    "EnvironmentKind",
    "EnvironmentManifest",
    "EnvironmentMountSpec",
    "EnvironmentName",
    "EnvironmentPreflight",
    "EnvironmentPreflightError",
    "EnvironmentPreflightResult",
    "EnvironmentPreflightSpec",
    "EnvironmentRepositorySpec",
    "EnvironmentResponsibleParty",
    "EnvironmentSecretSpec",
    "EnvironmentVariable",
    "EvidenceArtifact",
    "EvidenceFreshness",
    "EvidenceWorkProduct",
    "Error",
    "ErrorCategory",
    "ErrorCode",
    "Failure",
    "Factory",
    "FactoryBudgetPeriod",
    "FactoryBudgetPolicy",
    "FactoryId",
    "FactoryKind",
    "FactoryLunaRole",
    "FactoryPatch",
    "FactoryResultAuthorityGeneration",
    "FactoryRoleReceiptMintRequest",
    "FactoryRoleReceiptProvenance",
    "FactoryRoleReceiptResponse",
    "FactoryRoleReceiptRuntimeEvidence",
    "FactorySpec",
    "FactoryTransition",
    "FactoryTraceStoreAPI",
    "FundingSource",
    "ExecutionCapability",
    "ExecutionProfile",
    "HostKind",
    "InferenceProvider",
    "LocalExecution",
    "OpenEndedQuestionSpec",
    "ActorHarness",
    "ActorImageBinding",
    "ActorModel",
    "KickoffArtifact",
    "KickoffMessage",
    "KickoffMessageMode",
    "PlatformResolvedExecutionTarget",
    "PrimaryParentKind",
    "PrimaryParentRef",
    "ProviderBinding",
    "ProviderPolicy",
    "RoleBinding",
    "RoleBindings",
    "WorkerRolePalette",
    "WorkMode",
    "CraftaxScorerImageRelease",
    "CraftaxScorerImageReleaseDeclaration",
    "ImageRelease",
    "ImageReleaseDeclaration",
    "ImageReleaseFinalize",
    "ImageReleaseFinalizeRequest",
    "ImageReleaseFinalizeResponse",
    "ImageReleaseId",
    "ImageReleaseKind",
    "ImageReleaseStorageIdentity",
    "ImageReleaseUpload",
    "ImageReleaseUploadReconciliation",
    "ImageReleaseUploadRequest",
    "ImageReleaseUploadResponse",
    "ImageUploadId",
    "Limit",
    "MessageId",
    "ParticipantSessionId",
    "Preflight",
    "Project",
    "ProjectComputerAPI",
    "ProjectComputerCleanupReceiptResponse",
    "ProjectComputerCleanupRequest",
    "ProjectComputerExecuteRequest",
    "ProjectComputerInspectRequest",
    "ProjectComputerLeaseAcquireRequest",
    "ProjectComputerLeaseReleaseRequest",
    "ProjectComputerLeaseRenewRequest",
    "ProjectComputerLeaseResponse",
    "ProjectComputerLifecycle",
    "ProjectComputerOperationReconcileRequest",
    "ProjectComputerProvisionRequest",
    "ProjectComputerProvisionReceipt",
    "ProjectComputerReplaceRequest",
    "ProjectComputerResponse",
    "ProjectComputerRestorationReceipt",
    "ProjectComputerRetirementReceipt",
    "ProjectComputerWorkspaceSnapshot",
    "ProjectDeliveriesAPI",
    "ProjectRuntimeOperationReceipt",
    "ProjectDataBindingsAPI",
    "ProjectDataset",
    "ProjectDatasetEncoding",
    "ProjectDatasetId",
    "ProjectDatasetSourceKind",
    "ProjectDatasetUpload",
    "ProjectEventId",
    "ProjectId",
    "ProjectPatch",
    "ProjectSpec",
    "ProjectRepository",
    "ProjectRepositoryDeletion",
    "ProjectRepositoryId",
    "ProjectRepositoryPatch",
    "ProjectRepositoryRole",
    "ProjectRepositoryScope",
    "ProjectRepositorySpec",
    "ProjectWorkspaceInputs",
    "ResolvedSwarmConfiguration",
    "RuntimeKind",
    "RuntimeImageReleaseArchiveResponse",
    "RuntimeImageReleaseId",
    "RuntimeImageReleaseListResponse",
    "RuntimeImageReleaseStatus",
    "RuntimeImageKind",
    "RuntimeImageRef",
    "Retry",
    "ResearchTracesAPI",
    "ResearchInternAPI",
    "ResearchInternFactoryMembershipResponse",
    "ResearchInternPatchRequest",
    "ResearchInternPolicySet",
    "ResearchInternProvisionRequest",
    "ResearchInternResponse",
    "ResearchInternStatus",
    "ResearchVisual",
    "ResearchVisualPage",
    "ResearchVisualPatchRequest",
    "ResearchVisualPromotionRequest",
    "ResearchVisualVersions",
    "ResourceMetadata",
    "ResourceProvider",
    "ResourceRoutingPolicy",
    "RunPolicy",
    "RunPolicyAccess",
    "RunPolicyLimits",
    "Runbook",
    "Swarm",
    "SwarmActivity",
    "SwarmEvidence",
    "SwarmEvent",
    "SwarmEventKind",
    "SwarmHeartbeat",
    "SwarmHandle",
    "SwarmId",
    "SwarmLivenessPhase",
    "SwarmRuntimeSnapshot",
    "SwarmSpec",
    "SwarmState",
    "SwarmEnvironment",
    "SwarmTranscriptEvent",
    "SwarmTranscriptPage",
    "SwarmUsage",
    "TaskId",
    "ToolProvider",
    "TokenCounts",
    "TokenUsage",
    "TraceBundleDownload",
    "TraceBundleDownloadObject",
    "TraceBundleObjectDeclaration",
    "TraceBundleObjectKind",
    "TraceBundlePrepareRequest",
    "TraceBundlePublication",
    "TraceBundlePublicationLineage",
    "TraceBundlePublicationStatus",
    "TraceBundleSourceArtifactRef",
    "TraceCatalogProvider",
    "TraceDownload",
    "TraceEvidenceAuthorityRef",
    "TraceExperimentRevisionRef",
    "TraceObjectUpload",
    "TracePromotionReceipt",
    "TraceQueryResult",
    "TraceRecordSummary",
    "TraceStoreAccessReceipt",
    "TraceStoreDescriptor",
    "TraceStoreLifecycleReceipt",
    "TraceStoreProvisionResult",
    "TraceStoreProvisioningStatus",
    "TranscriptCursor",
    "TranscriptCursorKind",
    "TranscriptEventId",
    "TranscriptFreshness",
    "TranscriptParticipant",
    "TranscriptPayloadClassification",
    "TranscriptProjectionAuthority",
    "TranscriptRedactionProfile",
    "TranscriptReplayMode",
    "TranscriptView",
    "TranscriptVisibilityDecision",
    "UsageFreshness",
    "UsageMoney",
    "UsageSource",
    "UserId",
    "Visual",
    "VisualBlobState",
    "VisualEvidencePayload",
    "VisualPage",
    "VisualPatch",
    "VisualPromotion",
    "VisualStatus",
    "VisualVisibility",
    "VisualVersions",
    "VisualsAPI",
    "WORKSPACE_BATCH_UPLOAD_FILE_LIMIT",
    "WORKSPACE_UPLOAD_FILE_LIMIT",
    "WorkspaceBatchUploadError",
    "WorkspaceFileEncoding",
    "WorkspaceFileId",
    "WorkspaceFileKind",
    "WorkspaceFileScope",
    "WorkspaceFilesBatchUploadProgress",
    "WorkspaceFilesBatchUploadReceipt",
    "WorkspaceFilesBatchUploadRequest",
    "WorkspaceFilesUploadReceipt",
    "WorkspaceFilesUploadRequest",
    "WorkspaceFileUpload",
    "WorkspaceFileVisibility",
    "WorkspaceInputState",
    "WorkspacePushConfirmationReceipt",
    "WorkspaceMetadata",
    "WorkspaceProjectRepository",
    "WorkspaceRepositoryAuthMode",
    "WorkspaceRepositoryBootstrapMode",
    "WorkspaceSourceRepository",
    "WorkspaceSourceRepositoryKind",
    "WorkspaceSourceRepositoryReceipt",
    "WorkspaceSourceRepositorySpec",
    "WorkspaceStoredFile",
    "WorkMode",
    "WorkProductArtifactLink",
    "WorkProductArtifactRole",
    "WorkProductBlocker",
    "WorkProductId",
    "WorkProductKind",
    "WorkProductReadiness",
    "WorkProductStatus",
]

_COMPATIBILITY_EXPORTS: dict[str, tuple[str, str]] = {
    "AsyncResearchClient": ("synth_ai.core.research.client", "AsyncResearchClient"),
    "ResearchApiError": ("synth_ai.core.research.errors", "ResearchApiError"),
    "ResearchArtifact": ("synth_ai.core.research.models", "ResearchArtifact"),
    "ResearchArtifactManifest": ("synth_ai.core.research.models", "ResearchArtifactManifest"),
    "ResearchAgentHarness": ("synth_ai.core.research.contracts", "ActorHarness"),
    "ResearchAgentModel": ("synth_ai.core.research.contracts", "ActorModel"),
    "ResearchAgentProfileBindings": (
        "synth_ai.core.research.models",
        "ResearchAgentProfileBindings",
    ),
    "ResearchAuthorityReadouts": (
        "synth_ai.core.research.models",
        "ResearchAuthorityReadouts",
    ),
    "ResearchBillingCatalog": ("synth_ai.core.research.models", "ResearchBillingCatalog"),
    "ResearchBillingDrawdown": ("synth_ai.core.research.models", "ResearchBillingDrawdown"),
    "ResearchBillingEntitlements": (
        "synth_ai.core.research.models",
        "ResearchBillingEntitlements",
    ),
    "ResearchBillingPlan": ("synth_ai.core.research.models", "ResearchBillingPlan"),
    "ResearchClient": ("synth_ai.core.research.facade", "ResearchClient"),
    "ResearchConcurrentRunLimitExceededError": (
        "synth_ai.core.research.errors",
        "ResearchConcurrentRunLimitExceededError",
    ),
    "ResearchEconomicsAPI": ("synth_ai.core.research.economics", "ResearchEconomicsAPI"),
    "ResearchEnvironmentKind": ("synth_ai.core.research.contracts", "EnvironmentKind"),
    "ResearchFactoriesAPI": ("synth_ai.core.research.factories", "ResearchFactoriesAPI"),
    "ResearchHostKind": ("synth_ai.core.research.contracts", "HostKind"),
    "ResearchInsufficientCreditsError": (
        "synth_ai.core.research.errors",
        "ResearchInsufficientCreditsError",
    ),
    "ResearchLimitExceededError": (
        "synth_ai.core.research.errors",
        "ResearchLimitExceededError",
    ),
    "ResearchLimitsAPI": ("synth_ai.core.research.economics", "ResearchLimitsAPI"),
    "ResearchOrgLimits": ("synth_ai.core.research.models", "ResearchOrgLimits"),
    "ResearchProject": ("synth_ai.core.research.contracts", "ResearchProject"),
    "ResearchProjectCreateRequest": (
        "synth_ai.core.research.contracts",
        "ResearchProjectCreateRequest",
    ),
    "ResearchProjectPatchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchProjectPatchRequest",
    ),
    "ResearchProjectEconomics": (
        "synth_ai.core.research.models",
        "ResearchProjectEconomics",
    ),
    "ResearchProjectMonthlyBudgetExhaustedError": (
        "synth_ai.core.research.errors",
        "ResearchProjectMonthlyBudgetExhaustedError",
    ),
    "ResearchProjectsAPI": ("synth_ai.core.research.projects", "ResearchProjectsAPI"),
    "ResearchRoleBinding": ("synth_ai.core.research.models", "ResearchRoleBinding"),
    "ResearchRoleBindings": ("synth_ai.core.research.models", "ResearchRoleBindings"),
    "ResearchRun": ("synth_ai.core.research.models", "ResearchRun"),
    "ResearchRunHandle": ("synth_ai.core.research.advanced_swarms", "ResearchRunHandle"),
    "ResearchRunLaunchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchRunLaunchRequest",
    ),
    "ResearchRunProgress": ("synth_ai.core.research.models", "ResearchRunProgress"),
    "ResearchRunSession": ("synth_ai.core.research.advanced_swarms", "ResearchRunSession"),
    "ResearchRunbookPreset": ("synth_ai.core.research.models", "ResearchRunbookPreset"),
    "ResearchRunnableProjectRequest": (
        "synth_ai.core.research.contracts",
        "ResearchProjectCreateRequest",
    ),
    "ResearchRunsAPI": ("synth_ai.core.research.advanced_swarms", "ResearchRunsAPI"),
    "ResearchRuntimeKind": ("synth_ai.core.research.contracts", "RuntimeKind"),
    "ResearchSecretsAPI": ("synth_ai.core.research.secrets", "ResearchSecretsAPI"),
    "ResearchStructuredDenialError": (
        "synth_ai.core.research.errors",
        "ResearchStructuredDenialError",
    ),
    "ResearchSwarm": ("synth_ai.core.research.contracts", "ResearchSwarm"),
    "ResearchSwarmBranchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmBranchRequest",
    ),
    "ResearchSwarmBranchResult": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmBranchResult",
    ),
    "ResearchSwarmHandle": ("synth_ai.core.research.swarms", "ResearchSwarmHandle"),
    "ResearchSwarmLaunchRequest": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmLaunchRequest",
    ),
    "ResearchSwarmPreflight": (
        "synth_ai.core.research.contracts",
        "ResearchSwarmPreflight",
    ),
    "ResearchSwarmState": ("synth_ai.core.research.contracts", "ResearchSwarmState"),
    "ResearchSwarmsAPI": ("synth_ai.core.research.swarms", "ResearchSwarmsAPI"),
    "ResearchTagSessionCreateRequest": (
        "synth_ai.core.research.models",
        "ResearchTagSessionCreateRequest",
    ),
    "ResearchWorkMode": ("synth_ai.core.research.contracts", "WorkMode"),
    "ResearchWorkerRolePalette": (
        "synth_ai.core.research.models",
        "ResearchWorkerRolePalette",
    ),
    "ResearchWorkProduct": ("synth_ai.core.research.models", "ResearchWorkProduct"),
    "ResourceLimit": ("synth_ai.core.research.contracts", "ResourceLimit"),
}


def __getattr__(name: str) -> object:
    target = _COMPATIBILITY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attribute = target
    value = getattr(importlib.import_module(module_name), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
