# Configuration for Multi-Model Crafter Evaluation

[experiment]
# Number of episodes to run per model
episodes = 10

# Maximum turns per episode
max_turns = 100

# Difficulty level (easy, medium, hard)
difficulty = "easy"

# Models to test (can be overridden with --models CLI argument)
models = [
    "gpt-4o-mini",
    "gpt-4.1-mini", 
    "gpt-4.1-nano",
    "gemini-1.5-flash",
    "gemini-2.5-flash-lite",
    "qwen3/32b"
]

# Concurrency settings
concurrent_models = false  # Whether to run models concurrently
max_concurrent_models = 3  # Maximum number of models to run at once

[services]
# Crafter environment service URL
crafter_service_url = "http://localhost:8901"

# Database path for storing traces
database_path = "crafter_multi_model_traces.duckdb"

[output]
# Directory for saving traces and results
trace_dir = "./traces_multi_model"

# Whether to save detailed traces
save_traces = true

# Whether to enable verbose output
verbose = true

[http]
# HTTP timeout in seconds
timeout = 30.0

# Maximum retries for failed requests
max_retries = 3 