# Crafter eval using Synth backend with Qwen3-4B

[eval]
app_id = "grpo-crafter-task-app"
task_app_url = "https://synth-laboratories--grpo-crafter-task-app-fastapi-app-dev.modal.run"
model = "Qwen/Qwen3-4B"
seeds = [0, 1, 2]
max_turns = 10
concurrency = 1
env_name = "crafter"
policy_name = "crafter-react"
trace_format = "full"
return_trace = true

[eval.env_config]
env_params = {max_steps_per_episode = 10}

[eval.policy_config]
provider = "openai"
model = "Qwen/Qwen3-4B"
inference_url = "https://synth-backend-dev-docker.onrender.com/api/v1/chat/completions"
temperature = 0.6
top_p = 0.95
max_tokens = 512
use_vision = false
image_only_mode = false
max_llm_calls = 10

[eval.judge]
path = "examples/multi_step/judges/crafter_backend_judge.py"
name = "Backend"
backend_url = "http://localhost:8000/api"
model = "openai/gpt-oss-120b"
timeout_s = 45

