"""Public Research types for ``SynthClient().research``.

The hero workflow is ``Project -> Swarm -> events/result``.  Factory is the
durable optimization loop that creates and evaluates Efforts.  Names prefixed with
``Research`` are the canonical domain vocabulary.
"""

from __future__ import annotations

import importlib

from synth_ai.core.errors import (
    RetryDirective as Retry,
)
from synth_ai.core.errors import (
    SynthError as Error,
)
from synth_ai.core.errors import (
    SynthErrorCategory as ErrorCategory,
)
from synth_ai.core.errors import (
    SynthErrorCode as ErrorCode,
)
from synth_ai.core.errors import (
    SynthFailure as Failure,
)
from synth_ai.sdk.research.client import AsyncClient
from synth_ai.sdk.research.contracts import (
    ENVIRONMENT_SCHEMA_VERSION,
    MAGI_CANONICAL_USER_BY_MODE,
    WORKSPACE_BATCH_UPLOAD_FILE_LIMIT,
    WORKSPACE_UPLOAD_FILE_LIMIT,
    ActiveActorModel,
    ActivityActor,
    ActivityActorState,
    ActivityCursor,
    ActivityEvent,
    ActivityEventId,
    ActivityMessage,
    ActivityRun,
    ActivityTask,
    ActivityTaskState,
    ActivityWindow,
    ActivityWindowReceipt,
    ActivityWorkProduct,
    ActorFailureReason,
    ActorHarness,
    ActorId,
    ActorImageBinding,
    ActorModel,
    ActorRuntimeImageMaterialization,
    ActorRuntimeImageRelease,
    ActorRuntimeImageReleaseArchive,
    ActorRuntimeImageReleaseDeclaration,
    ActorRuntimeImageReleaseList,
    ActorTokenUsage,
    ActorUsage,
    ActorUsageMoney,
    ArtifactId,
    BoundRuntimeExecutionTarget,
    BranchSpec,
    BudgetPolicy,
    CapacityPolicy,
    ConfigurationVersionId,
    ContentDisposition,
    CraftaxScorerImageRelease,
    CraftaxScorerImageReleaseDeclaration,
    CredentialProvider,
    DataBindingCreateRequest,
    DataBindingResponse,
    DatasetRevisionCreateRequest,
    DatasetRevisionFinalizeRequest,
    DatasetRevisionFinalizeResponse,
    DatasetRevisionLifecycleRequest,
    DatasetRevisionPreparationResponse,
    DatasetRevisionPrepareRequest,
    DatasetRevisionResponse,
    Delivery,
    DeliveryReceipt,
    DeprecatedActorModel,
    DirectedEffortOutcomeSpec,
    DraftDeliveryAuthorityResponse,
    Effort,
    EffortBudgetPolicy,
    EffortId,
    EffortMaintenanceRecurrencePolicy,
    EffortPatch,
    EffortRecurrence,
    EffortResearchRecurrencePolicy,
    EffortRunClass,
    EffortSpec,
    EffortType,
    EnsureDraftDeliveryRequest,
    Environment,
    EnvironmentDetail,
    EnvironmentDigest,
    EnvironmentId,
    EnvironmentIsolationSpec,
    EnvironmentJsonObject,
    EnvironmentKind,
    EnvironmentManifest,
    EnvironmentMountSpec,
    EnvironmentName,
    EnvironmentPreflight,
    EnvironmentPreflightError,
    EnvironmentPreflightResult,
    EnvironmentPreflightSpec,
    EnvironmentRepositorySpec,
    EnvironmentResponsibleParty,
    EnvironmentSecretSpec,
    EnvironmentVariable,
    EvidenceArtifact,
    EvidenceFreshness,
    EvidenceWorkProduct,
    ExecutionCapability,
    ExecutionProfile,
    Factory,
    FactoryBudgetPeriod,
    FactoryBudgetPolicy,
    FactoryId,
    FactoryKind,
    FactoryLunaRole,
    FactoryPatch,
    FactoryResultAuthorityGeneration,
    FactoryRoleReceiptMintRequest,
    FactoryRoleReceiptProvenance,
    FactoryRoleReceiptResponse,
    FactoryRoleReceiptRuntimeEvidence,
    FactorySpec,
    FactoryStorageAuthorityResponse,
    FactoryTransition,
    FundingSource,
    HostKind,
    ImageRelease,
    ImageReleaseDeclaration,
    ImageReleaseFinalize,
    ImageReleaseFinalizeRequest,
    ImageReleaseFinalizeResponse,
    ImageReleaseId,
    ImageReleaseKind,
    ImageReleaseStorageIdentity,
    ImageReleaseUpload,
    ImageReleaseUploadReconciliation,
    ImageReleaseUploadRequest,
    ImageReleaseUploadResponse,
    ImageUploadId,
    InferenceProvider,
    InternAcceptanceFixtureReceipt,
    InternAcceptanceFixtureRequest,
    InternAcceptanceFixtureResource,
    InternAgentConfig,
    InternAsyncBlocker,
    InternAsyncCheckpoint,
    InternAsyncCommandKind,
    InternAsyncCommandReceipt,
    InternAsyncCommandRequest,
    InternAsyncEffortWorkSummary,
    InternAsyncEnsureRequest,
    InternAsyncEvent,
    InternAsyncEventPage,
    InternAsyncEventStreamEnvelope,
    InternAsyncEvidenceReadiness,
    InternAsyncExternalExecutionStatus,
    InternAsyncHandoffModelRequest,
    InternAsyncHandoffReviewRequest,
    InternAsyncInstructionKind,
    InternAsyncInstructionRequest,
    InternAsyncJudgmentItem,
    InternAsyncResumeKind,
    InternAsyncRuntime,
    InternAsyncRuntimeBudget,
    InternAsyncRuntimeHostLease,
    InternAsyncRuntimePhase,
    InternAsyncRuntimeSpend,
    InternAsyncStatus,
    InternAsyncStopReason,
    InternAsyncWaitProducer,
    InternCrossMetaThreadMessage,
    InternCrossMetaThreadMessageCreateRequest,
    InternCrossMetaThreadMessageKind,
    InternCrossMetaThreadMessageResolution,
    InternEffortBoardResponse,
    InternEffortClaimProgress,
    InternEffortDetailResponse,
    InternEffortEvidenceRef,
    InternEffortExperiment,
    InternEffortExperimentsRollup,
    InternEffortKnowledgeRollup,
    InternEffortLinkedRun,
    InternEffortLogEntry,
    InternEffortMemoryHit,
    InternEffortMilestoneProgress,
    InternEffortObjectiveProgress,
    InternEffortOpenQuestion,
    InternEffortProgressRollup,
    InternEffortRef,
    InternEffortReportRef,
    InternEffortResultsRollup,
    InternEffortRuntimeStrip,
    InternEffortSpend,
    InternEffortStickyHost,
    InternEffortSummary,
    InternEffortTaskCreateRequest,
    InternEffortTaskPatchRequest,
    InternEffortTaskProgress,
    InternEffortTaskResponse,
    InternEffortTaskState,
    InternEffortWorkProduct,
    InternEffortWorkSummary,
    InternMemoryHit,
    InternMemoryHitKind,
    InternMemoryHitResponse,
    InternMemorySearchResponse,
    InternMetaHandoff,
    InternMetaHandoffStatus,
    InternMetaThread,
    InternMetaThreadKind,
    InternMetaThreadLifecycle,
    InternMetaThreadSegment,
    InternMetaThreadSegmentStatus,
    InternMilestoneCreateRequest,
    InternMilestoneResponse,
    InternMilestoneState,
    InternMilestoneTransitionRequest,
    InternObjectiveCreateRequest,
    InternObjectiveKind,
    InternObjectiveLinkCreateRequest,
    InternObjectiveLinkResponse,
    InternObjectivePatchRequest,
    InternObjectiveResponse,
    InternObjectiveStatus,
    InternProducedResourceKind,
    InternProducedResourceReference,
    InternProgressClaimCreateRequest,
    InternProgressClaimResponse,
    InternRuntimeBinding,
    InternRuntimeOutcome,
    InternSyncCommandKind,
    InternSyncCommandReceipt,
    InternSyncCommandRequest,
    InternSyncDeployPacket,
    InternSyncDeployPacketEndpoint,
    InternSyncEvent,
    InternSyncEventPage,
    InternSyncEventStreamEnvelope,
    InternSyncSession,
    InternSyncSessionCreateRequest,
    InternSyncStatus,
    KickoffArtifact,
    KickoffMessage,
    KickoffMessageMode,
    LocalExecution,
    MagiActuationStatus,
    MagiCanonicalUser,
    MagiDecisionActuationReceipt,
    MagiDecisionKind,
    MagiDecisionReceiptResponse,
    MagiDecisionRequest,
    MagiMode,
    ManagedResearchFailureClassification,
    ManagedResearchFailureFamily,
    ManagedResearchFailureScope,
    ManagedResearchFailureSeverity,
    MessageId,
    OpenEndedQuestionSpec,
    ParticipantSessionId,
    PlatformResolvedExecutionTarget,
    PrimaryParentKind,
    PrimaryParentRef,
    Project,
    ProjectComputerCleanupReceiptResponse,
    ProjectComputerCleanupRequest,
    ProjectComputerExecuteRequest,
    ProjectComputerInspectRequest,
    ProjectComputerLeaseAcquireRequest,
    ProjectComputerLeaseReleaseRequest,
    ProjectComputerLeaseRenewRequest,
    ProjectComputerLeaseResponse,
    ProjectComputerLifecycle,
    ProjectComputerOperationReconcileRequest,
    ProjectComputerProvisionReceipt,
    ProjectComputerProvisionRequest,
    ProjectComputerReplaceRequest,
    ProjectComputerResponse,
    ProjectComputerRestorationReceipt,
    ProjectComputerRetirementReceipt,
    ProjectComputerWorkspaceSnapshot,
    ProjectDataset,
    ProjectDatasetEncoding,
    ProjectDatasetId,
    ProjectDatasetSourceKind,
    ProjectDatasetUpload,
    ProjectEventId,
    ProjectId,
    ProjectPatch,
    ProjectRepository,
    ProjectRepositoryDeletion,
    ProjectRepositoryId,
    ProjectRepositoryPatch,
    ProjectRepositoryRole,
    ProjectRepositoryScope,
    ProjectRepositorySpec,
    ProjectRuntimeOperationReceipt,
    ProjectSpec,
    ProjectWorkspaceInputs,
    ProviderBinding,
    ProviderPolicy,
    RegistryActorRuntimeImageRegistration,
    RegistryActorRuntimeImageRegistrationRequest,
    ResearchInternAcceptanceReceiptPublicationRequest,
    ResearchInternAcceptanceReceiptPublicationResponse,
    ResearchInternFactoryMembershipResponse,
    ResearchInternPatchRequest,
    ResearchInternPolicySet,
    ResearchInternProvisionRequest,
    ResearchInternResponse,
    ResearchInternStatus,
    ResearchVisual,
    ResearchVisualPage,
    ResearchVisualPatchRequest,
    ResearchVisualPromotionRequest,
    ResearchVisualVersions,
    ResolvedSwarmConfiguration,
    ResourceMetadata,
    ResourceProvider,
    ResourceRoutingPolicy,
    RoleBinding,
    RoleBindings,
    Runbook,
    RunPolicy,
    RunPolicyAccess,
    RunPolicyLimits,
    RuntimeImageKind,
    RuntimeImageRef,
    RuntimeImageReleaseArchiveResponse,
    RuntimeImageReleaseId,
    RuntimeImageReleaseListResponse,
    RuntimeImageReleaseStatus,
    RuntimeKind,
    Swarm,
    SwarmActivity,
    SwarmEnvironment,
    SwarmEvidence,
    SwarmHeartbeat,
    SwarmId,
    SwarmLivenessPhase,
    SwarmRuntimeSnapshot,
    SwarmSpec,
    SwarmState,
    SwarmTranscriptEvent,
    SwarmTranscriptPage,
    SwarmUsage,
    SyncTracePublicationReceipt,
    SyncWorkspaceRunReceipt,
    SyncWorkspaceSnapshotIdentity,
    SyncWorkspaceSnapshotKind,
    TaskId,
    TokenCounts,
    TokenUsage,
    ToolProvider,
    TraceBundleDownload,
    TraceBundleDownloadObject,
    TraceBundleObjectDeclaration,
    TraceBundleObjectKind,
    TraceBundlePrepareRequest,
    TraceBundlePublication,
    TraceBundlePublicationLineage,
    TraceBundlePublicationStatus,
    TraceBundleSourceArtifactRef,
    TraceCatalogProvider,
    TraceDownload,
    TraceEvidenceAuthorityRef,
    TraceExperimentRevisionRef,
    TraceObjectUpload,
    TracePromotionReceipt,
    TraceQueryResult,
    TraceRecordSummary,
    TraceStoreAccessReceipt,
    TraceStoreDescriptor,
    TraceStoreLifecycleReceipt,
    TraceStorePreflightRequest,
    TraceStorePreflightResponse,
    TraceStoreProvisioningStatus,
    TraceStoreProvisionResult,
    TraceStoreRunEnvelopeIdentity,
    TranscriptCursor,
    TranscriptCursorKind,
    TranscriptEventId,
    TranscriptFreshness,
    TranscriptParticipant,
    TranscriptPayloadClassification,
    TranscriptProjectionAuthority,
    TranscriptRedactionProfile,
    TranscriptReplayMode,
    TranscriptView,
    TranscriptVisibilityDecision,
    UsageFreshness,
    UsageMoney,
    UsageSource,
    UserId,
    Visual,
    VisualBlobState,
    VisualEvidencePayload,
    VisualPage,
    VisualPatch,
    VisualPromotion,
    VisualStatus,
    VisualVersions,
    VisualVisibility,
    WorkerRolePalette,
    WorkMode,
    WorkProductArtifactLink,
    WorkProductArtifactRole,
    WorkProductBlocker,
    WorkProductId,
    WorkProductKind,
    WorkProductReadiness,
    WorkProductStatus,
    WorkspaceFileEncoding,
    WorkspaceFileId,
    WorkspaceFileKind,
    WorkspaceFilesBatchUploadProgress,
    WorkspaceFilesBatchUploadReceipt,
    WorkspaceFilesBatchUploadRequest,
    WorkspaceFileScope,
    WorkspaceFilesUploadReceipt,
    WorkspaceFilesUploadRequest,
    WorkspaceFileUpload,
    WorkspaceFileVisibility,
    WorkspaceInputState,
    WorkspaceMetadata,
    WorkspaceProjectRepository,
    WorkspacePushConfirmationReceipt,
    WorkspaceRepositoryAuthMode,
    WorkspaceRepositoryBootstrapMode,
    WorkspaceSourceRepository,
    WorkspaceSourceRepositoryKind,
    WorkspaceSourceRepositoryReceipt,
    WorkspaceSourceRepositorySpec,
    WorkspaceStoredFile,
)
from synth_ai.sdk.research.contracts import (
    BranchResult as Branch,
)
from synth_ai.sdk.research.contracts import (
    ResourceLimit as Limit,
)
from synth_ai.sdk.research.contracts import (
    SwarmPreflight as Preflight,
)
from synth_ai.sdk.research.contracts.intern_grants import (
    INTERN_EFFORT_PROGRAM_CAPABILITIES,
    INTERN_EFFORT_PROGRAM_TOOL_CAPABILITIES,
    INTERN_KICKOFF_AND_POLL_TOOLS,
    InternCapabilityOperation,
    InternGrantError,
    InternMcpActionKind,
    intern_effort_program_grant,
    validate_intern_tool_grant,
)
from synth_ai.sdk.research.events import (
    SwarmEvent,
    SwarmEventKind,
)
from synth_ai.sdk.research.facade import Client
from synth_ai.sdk.research.factory_storage import (
    AsyncFactoryStorageAPI,
    FactoryStorageAPI,
)
from synth_ai.sdk.research.intern_program import (
    AsyncInternProgramAPI,
    InternProgramAPI,
)
from synth_ai.sdk.research.project_deliveries import (
    AsyncProjectDeliveriesAPI,
    ProjectDeliveriesAPI,
)
from synth_ai.sdk.research.project_workspaces import WorkspaceBatchUploadError
from synth_ai.sdk.research.research_intern import (
    AsyncProjectComputerAPI,
    AsyncProjectDataBindingsAPI,
    AsyncResearchInternAcceptanceFixturesAPI,
    AsyncResearchInternAcceptanceReceiptsAPI,
    AsyncResearchInternAPI,
    AsyncResearchInternAsyncRuntimeAPI,
    AsyncResearchInternDecisionsAPI,
    AsyncResearchInternFactoriesAPI,
    AsyncResearchInternMetaThreadsAPI,
    AsyncResearchInternSyncRuntimeAPI,
    ProjectComputerAPI,
    ProjectDataBindingsAPI,
    ResearchInternAcceptanceFixturesAPI,
    ResearchInternAcceptanceReceiptsAPI,
    ResearchInternAPI,
    ResearchInternAsyncRuntimeAPI,
    ResearchInternDecisionsAPI,
    ResearchInternFactoriesAPI,
    ResearchInternMetaThreadsAPI,
    ResearchInternSyncRuntimeAPI,
)
from synth_ai.sdk.research.surface_parity import (
    CanonicalIdentity,
    SurfaceObservation,
    async_runtime_digest,
    build_surface_parity,
    canonical_digest,
    emit_surface_parity_json,
    sync_projection_digest,
)
from synth_ai.sdk.research.swarms import SwarmHandle
from synth_ai.sdk.research.traces import FactoryTraceStoreAPI, ResearchTracesAPI
from synth_ai.sdk.research.visuals import AsyncVisualsAPI, VisualsAPI

__all__ = [
    "ActiveActorModel",
    "AsyncResearchInternAcceptanceFixturesAPI",
    "InternAcceptanceFixtureReceipt",
    "InternAcceptanceFixtureRequest",
    "InternAcceptanceFixtureResource",
    "ActivityActor",
    "ActivityActorState",
    "ActivityCursor",
    "ActivityEvent",
    "ActivityEventId",
    "ActivityMessage",
    "ActivityRun",
    "ActivityTask",
    "ActivityTaskState",
    "ActivityWindow",
    "ActivityWindowReceipt",
    "ActivityWorkProduct",
    "ActorFailureReason",
    "ActorHarness",
    "ActorId",
    "ActorImageBinding",
    "ActorModel",
    "ActorRuntimeImageMaterialization",
    "ActorRuntimeImageRelease",
    "ActorRuntimeImageReleaseArchive",
    "ActorRuntimeImageReleaseDeclaration",
    "ActorRuntimeImageReleaseList",
    "ActorTokenUsage",
    "ActorUsage",
    "ActorUsageMoney",
    "ArtifactId",
    "AsyncClient",
    "AsyncFactoryStorageAPI",
    "AsyncInternProgramAPI",
    "AsyncProjectComputerAPI",
    "AsyncProjectDataBindingsAPI",
    "AsyncProjectDeliveriesAPI",
    "AsyncResearchInternAcceptanceReceiptsAPI",
    "AsyncResearchInternAPI",
    "AsyncResearchInternAsyncRuntimeAPI",
    "AsyncResearchInternDecisionsAPI",
    "AsyncResearchInternFactoriesAPI",
    "AsyncResearchInternMetaThreadsAPI",
    "AsyncResearchInternSyncRuntimeAPI",
    "AsyncVisualsAPI",
    "BoundRuntimeExecutionTarget",
    "Branch",
    "BranchSpec",
    "BudgetPolicy",
    "CapacityPolicy",
    "Client",
    "ConfigurationVersionId",
    "ContentDisposition",
    "CraftaxScorerImageRelease",
    "CraftaxScorerImageReleaseDeclaration",
    "CredentialProvider",
    "DataBindingCreateRequest",
    "DataBindingResponse",
    "DatasetRevisionCreateRequest",
    "DatasetRevisionFinalizeRequest",
    "DatasetRevisionFinalizeResponse",
    "DatasetRevisionLifecycleRequest",
    "DatasetRevisionPreparationResponse",
    "DatasetRevisionPrepareRequest",
    "DatasetRevisionResponse",
    "Delivery",
    "DeliveryReceipt",
    "DeprecatedActorModel",
    "DirectedEffortOutcomeSpec",
    "DraftDeliveryAuthorityResponse",
    "Effort",
    "EffortBudgetPolicy",
    "EffortId",
    "EffortMaintenanceRecurrencePolicy",
    "EffortPatch",
    "EffortRecurrence",
    "EffortResearchRecurrencePolicy",
    "EffortRunClass",
    "EffortSpec",
    "EffortType",
    "EnsureDraftDeliveryRequest",
    "Environment",
    "ENVIRONMENT_SCHEMA_VERSION",
    "EnvironmentDetail",
    "EnvironmentDigest",
    "EnvironmentId",
    "EnvironmentIsolationSpec",
    "EnvironmentJsonObject",
    "EnvironmentKind",
    "EnvironmentManifest",
    "EnvironmentMountSpec",
    "EnvironmentName",
    "EnvironmentPreflight",
    "EnvironmentPreflightError",
    "EnvironmentPreflightResult",
    "EnvironmentPreflightSpec",
    "EnvironmentRepositorySpec",
    "EnvironmentResponsibleParty",
    "EnvironmentSecretSpec",
    "EnvironmentVariable",
    "Error",
    "ErrorCategory",
    "ErrorCode",
    "EvidenceArtifact",
    "EvidenceFreshness",
    "EvidenceWorkProduct",
    "ExecutionCapability",
    "ExecutionProfile",
    "Factory",
    "FactoryBudgetPeriod",
    "FactoryBudgetPolicy",
    "FactoryId",
    "FactoryKind",
    "FactoryLunaRole",
    "FactoryPatch",
    "FactoryResultAuthorityGeneration",
    "FactoryRoleReceiptMintRequest",
    "FactoryRoleReceiptProvenance",
    "FactoryRoleReceiptResponse",
    "FactoryRoleReceiptRuntimeEvidence",
    "FactorySpec",
    "FactoryStorageAPI",
    "FactoryStorageAuthorityResponse",
    "FactoryTraceStoreAPI",
    "FactoryTransition",
    "Failure",
    "FundingSource",
    "HostKind",
    "ImageRelease",
    "ImageReleaseDeclaration",
    "ImageReleaseFinalize",
    "ImageReleaseFinalizeRequest",
    "ImageReleaseFinalizeResponse",
    "ImageReleaseId",
    "ImageReleaseKind",
    "ImageReleaseStorageIdentity",
    "ImageReleaseUpload",
    "ImageReleaseUploadReconciliation",
    "ImageReleaseUploadRequest",
    "ImageReleaseUploadResponse",
    "ImageUploadId",
    "InferenceProvider",
    "INTERN_EFFORT_PROGRAM_CAPABILITIES",
    "intern_effort_program_grant",
    "INTERN_EFFORT_PROGRAM_TOOL_CAPABILITIES",
    "INTERN_KICKOFF_AND_POLL_TOOLS",
    "InternAgentConfig",
    "InternAsyncBlocker",
    "InternAsyncCheckpoint",
    "InternAsyncCommandKind",
    "InternAsyncCommandReceipt",
    "InternAsyncCommandRequest",
    "InternAsyncEffortWorkSummary",
    "InternAsyncEnsureRequest",
    "InternAsyncEvent",
    "InternAsyncEventPage",
    "InternAsyncHandoffModelRequest",
    "InternAsyncHandoffReviewRequest",
    "InternAsyncEventStreamEnvelope",
    "InternAsyncEvidenceReadiness",
    "InternAsyncExternalExecutionStatus",
    "InternAsyncInstructionKind",
    "InternAsyncInstructionRequest",
    "InternAsyncJudgmentItem",
    "InternAsyncResumeKind",
    "InternAsyncRuntime",
    "InternAsyncRuntimeBudget",
    "InternAsyncRuntimeHostLease",
    "InternAsyncRuntimePhase",
    "InternAsyncRuntimeSpend",
    "InternAsyncStatus",
    "InternAsyncStopReason",
    "InternAsyncWaitProducer",
    "InternCapabilityOperation",
    "InternCrossMetaThreadMessage",
    "InternCrossMetaThreadMessageCreateRequest",
    "InternCrossMetaThreadMessageKind",
    "InternCrossMetaThreadMessageResolution",
    "InternEffortBoardResponse",
    "InternEffortClaimProgress",
    "InternEffortDetailResponse",
    "InternEffortEvidenceRef",
    "InternEffortExperiment",
    "InternEffortExperimentsRollup",
    "InternEffortKnowledgeRollup",
    "InternEffortLinkedRun",
    "InternEffortLogEntry",
    "InternEffortMemoryHit",
    "InternEffortMilestoneProgress",
    "InternEffortObjectiveProgress",
    "InternEffortOpenQuestion",
    "InternEffortProgressRollup",
    "InternEffortRef",
    "InternEffortReportRef",
    "InternEffortResultsRollup",
    "InternEffortRuntimeStrip",
    "InternEffortSpend",
    "InternEffortStickyHost",
    "InternEffortSummary",
    "InternEffortTaskCreateRequest",
    "InternEffortTaskPatchRequest",
    "InternEffortTaskProgress",
    "InternEffortTaskResponse",
    "InternEffortTaskState",
    "InternEffortWorkProduct",
    "InternEffortWorkSummary",
    "InternGrantError",
    "InternMcpActionKind",
    "InternMemoryHit",
    "InternMemoryHitKind",
    "InternMemoryHitResponse",
    "InternMemorySearchResponse",
    "InternMetaHandoff",
    "InternMetaHandoffStatus",
    "InternMetaThread",
    "InternMetaThreadKind",
    "InternMetaThreadLifecycle",
    "InternMetaThreadSegment",
    "InternMetaThreadSegmentStatus",
    "InternMilestoneCreateRequest",
    "InternMilestoneResponse",
    "InternMilestoneState",
    "InternMilestoneTransitionRequest",
    "InternObjectiveCreateRequest",
    "InternObjectiveKind",
    "InternObjectiveLinkCreateRequest",
    "InternObjectiveLinkResponse",
    "InternObjectivePatchRequest",
    "InternObjectiveResponse",
    "InternObjectiveStatus",
    "InternProducedResourceKind",
    "InternProducedResourceReference",
    "InternProgramAPI",
    "InternProgressClaimCreateRequest",
    "InternProgressClaimResponse",
    "InternRuntimeBinding",
    "InternRuntimeOutcome",
    "InternSyncCommandKind",
    "InternSyncCommandReceipt",
    "InternSyncCommandRequest",
    "InternSyncDeployPacket",
    "InternSyncDeployPacketEndpoint",
    "InternSyncEvent",
    "InternSyncEventPage",
    "InternSyncEventStreamEnvelope",
    "InternSyncSession",
    "InternSyncSessionCreateRequest",
    "InternSyncStatus",
    "KickoffArtifact",
    "KickoffMessage",
    "KickoffMessageMode",
    "Limit",
    "LocalExecution",
    "MAGI_CANONICAL_USER_BY_MODE",
    "MagiActuationStatus",
    "MagiCanonicalUser",
    "MagiDecisionActuationReceipt",
    "MagiDecisionKind",
    "MagiDecisionReceiptResponse",
    "MagiDecisionRequest",
    "MagiMode",
    "ManagedResearchFailureClassification",
    "ManagedResearchFailureFamily",
    "ManagedResearchFailureScope",
    "ManagedResearchFailureSeverity",
    "MessageId",
    "OpenEndedQuestionSpec",
    "ParticipantSessionId",
    "PlatformResolvedExecutionTarget",
    "Preflight",
    "PrimaryParentKind",
    "PrimaryParentRef",
    "Project",
    "ProjectComputerAPI",
    "ProjectComputerCleanupReceiptResponse",
    "ProjectComputerCleanupRequest",
    "ProjectComputerExecuteRequest",
    "ProjectComputerInspectRequest",
    "ProjectComputerLeaseAcquireRequest",
    "ProjectComputerLeaseReleaseRequest",
    "ProjectComputerLeaseRenewRequest",
    "ProjectComputerLeaseResponse",
    "ProjectComputerLifecycle",
    "ProjectComputerOperationReconcileRequest",
    "ProjectComputerProvisionReceipt",
    "ProjectComputerProvisionRequest",
    "ProjectComputerReplaceRequest",
    "ProjectComputerResponse",
    "ProjectComputerRestorationReceipt",
    "ProjectComputerRetirementReceipt",
    "ProjectComputerWorkspaceSnapshot",
    "ProjectDataBindingsAPI",
    "ProjectDataset",
    "ProjectDatasetEncoding",
    "ProjectDatasetId",
    "ProjectDatasetSourceKind",
    "ProjectDatasetUpload",
    "ProjectDeliveriesAPI",
    "ProjectEventId",
    "ProjectId",
    "ProjectPatch",
    "ProjectRepository",
    "ProjectRepositoryDeletion",
    "ProjectRepositoryId",
    "ProjectRepositoryPatch",
    "ProjectRepositoryRole",
    "ProjectRepositoryScope",
    "ProjectRepositorySpec",
    "ProjectRuntimeOperationReceipt",
    "ProjectSpec",
    "ProjectWorkspaceInputs",
    "ProviderBinding",
    "ProviderPolicy",
    "RegistryActorRuntimeImageRegistration",
    "RegistryActorRuntimeImageRegistrationRequest",
    "ResearchInternAcceptanceReceiptPublicationRequest",
    "ResearchInternAcceptanceReceiptPublicationResponse",
    "ResearchInternAcceptanceFixturesAPI",
    "ResearchInternAcceptanceReceiptsAPI",
    "ResearchInternAPI",
    "ResearchInternAsyncRuntimeAPI",
    "ResearchInternDecisionsAPI",
    "ResearchInternFactoriesAPI",
    "ResearchInternFactoryMembershipResponse",
    "ResearchInternMetaThreadsAPI",
    "ResearchInternPatchRequest",
    "ResearchInternPolicySet",
    "ResearchInternProvisionRequest",
    "ResearchInternResponse",
    "ResearchInternStatus",
    "ResearchInternSyncRuntimeAPI",
    "ResearchTracesAPI",
    "ResearchVisual",
    "ResearchVisualPage",
    "ResearchVisualPatchRequest",
    "ResearchVisualPromotionRequest",
    "ResearchVisualVersions",
    "ResolvedSwarmConfiguration",
    "ResourceMetadata",
    "ResourceProvider",
    "ResourceRoutingPolicy",
    "Retry",
    "RoleBinding",
    "RoleBindings",
    "Runbook",
    "RunPolicy",
    "RunPolicyAccess",
    "RunPolicyLimits",
    "RuntimeImageKind",
    "RuntimeImageRef",
    "RuntimeImageReleaseArchiveResponse",
    "RuntimeImageReleaseId",
    "RuntimeImageReleaseListResponse",
    "RuntimeImageReleaseStatus",
    "RuntimeKind",
    "Swarm",
    "SwarmActivity",
    "SwarmEnvironment",
    "SwarmEvent",
    "SwarmEventKind",
    "SwarmEvidence",
    "SwarmHandle",
    "SwarmHeartbeat",
    "SwarmId",
    "SwarmLivenessPhase",
    "SwarmRuntimeSnapshot",
    "SwarmSpec",
    "SwarmState",
    "SwarmTranscriptEvent",
    "SwarmTranscriptPage",
    "SwarmUsage",
    "SyncTracePublicationReceipt",
    "SyncWorkspaceRunReceipt",
    "SyncWorkspaceSnapshotIdentity",
    "SyncWorkspaceSnapshotKind",
    "TaskId",
    "TokenCounts",
    "TokenUsage",
    "ToolProvider",
    "TraceBundleDownload",
    "TraceBundleDownloadObject",
    "TraceBundleObjectDeclaration",
    "TraceBundleObjectKind",
    "TraceBundlePrepareRequest",
    "TraceBundlePublication",
    "TraceBundlePublicationLineage",
    "TraceBundlePublicationStatus",
    "TraceBundleSourceArtifactRef",
    "TraceCatalogProvider",
    "TraceDownload",
    "TraceEvidenceAuthorityRef",
    "TraceExperimentRevisionRef",
    "TraceObjectUpload",
    "TracePromotionReceipt",
    "TraceQueryResult",
    "TraceRecordSummary",
    "TraceStoreAccessReceipt",
    "TraceStoreDescriptor",
    "TraceStoreLifecycleReceipt",
    "TraceStoreProvisioningStatus",
    "TraceStoreProvisionResult",
    "TraceStorePreflightRequest",
    "TraceStorePreflightResponse",
    "TraceStoreRunEnvelopeIdentity",
    "TranscriptCursor",
    "TranscriptCursorKind",
    "TranscriptEventId",
    "TranscriptFreshness",
    "TranscriptParticipant",
    "TranscriptPayloadClassification",
    "TranscriptProjectionAuthority",
    "TranscriptRedactionProfile",
    "TranscriptReplayMode",
    "TranscriptView",
    "TranscriptVisibilityDecision",
    "UsageFreshness",
    "UsageMoney",
    "UsageSource",
    "UserId",
    "validate_intern_tool_grant",
    "Visual",
    "VisualBlobState",
    "VisualEvidencePayload",
    "VisualPage",
    "VisualPatch",
    "VisualPromotion",
    "VisualsAPI",
    "VisualStatus",
    "VisualVersions",
    "VisualVisibility",
    "WorkerRolePalette",
    "WorkMode",
    "WorkProductArtifactLink",
    "WorkProductArtifactRole",
    "WorkProductBlocker",
    "WorkProductId",
    "WorkProductKind",
    "WorkProductReadiness",
    "WorkProductStatus",
    "WORKSPACE_BATCH_UPLOAD_FILE_LIMIT",
    "WORKSPACE_UPLOAD_FILE_LIMIT",
    "WorkspaceBatchUploadError",
    "WorkspaceFileEncoding",
    "WorkspaceFileId",
    "WorkspaceFileKind",
    "WorkspaceFilesBatchUploadProgress",
    "WorkspaceFilesBatchUploadReceipt",
    "WorkspaceFilesBatchUploadRequest",
    "WorkspaceFileScope",
    "WorkspaceFilesUploadReceipt",
    "WorkspaceFilesUploadRequest",
    "WorkspaceFileUpload",
    "WorkspaceFileVisibility",
    "WorkspaceInputState",
    "WorkspaceMetadata",
    "WorkspaceProjectRepository",
    "WorkspacePushConfirmationReceipt",
    "WorkspaceRepositoryAuthMode",
    "WorkspaceRepositoryBootstrapMode",
    "WorkspaceSourceRepository",
    "WorkspaceSourceRepositoryKind",
    "WorkspaceSourceRepositoryReceipt",
    "WorkspaceSourceRepositorySpec",
    "WorkspaceStoredFile",
    # Surface-parity evidence helpers (Gate-2 WS3): one canonical digest and
    # one surfaces-object emitter shared by API/SDK/MCP parity checks.
    "CanonicalIdentity",
    "SurfaceObservation",
    "async_runtime_digest",
    "build_surface_parity",
    "canonical_digest",
    "emit_surface_parity_json",
    "sync_projection_digest",
]

_COMPATIBILITY_EXPORTS: dict[str, tuple[str, str]] = {
    "AsyncResearchClient": ("synth_ai.sdk.research.client", "AsyncClient"),
    "ResearchApiError": ("synth_ai.sdk.research.errors", "ResearchApiError"),
    "ResearchArtifact": ("synth_ai.sdk.research.models", "ResearchArtifact"),
    "ResearchArtifactManifest": ("synth_ai.sdk.research.models", "ResearchArtifactManifest"),
    "ResearchAgentHarness": ("synth_ai.sdk.research.contracts", "ActorHarness"),
    "ResearchAgentModel": ("synth_ai.sdk.research.contracts", "ActorModel"),
    "ResearchAgentProfileBindings": (
        "synth_ai.sdk.research.models",
        "ResearchAgentProfileBindings",
    ),
    "ResearchAuthorityReadouts": (
        "synth_ai.sdk.research.models",
        "ResearchAuthorityReadouts",
    ),
    "ResearchBillingCatalog": ("synth_ai.sdk.research.models", "ResearchBillingCatalog"),
    "ResearchBillingDrawdown": ("synth_ai.sdk.research.models", "ResearchBillingDrawdown"),
    "ResearchBillingEntitlements": (
        "synth_ai.sdk.research.models",
        "ResearchBillingEntitlements",
    ),
    "ResearchBillingPlan": ("synth_ai.sdk.research.models", "ResearchBillingPlan"),
    "ResearchClient": ("synth_ai.sdk.research.facade", "ResearchClient"),
    "ResearchConcurrentRunLimitExceededError": (
        "synth_ai.sdk.research.errors",
        "ResearchConcurrentRunLimitExceededError",
    ),
    "ResearchEconomicsAPI": ("synth_ai.sdk.research.economics", "ResearchEconomicsAPI"),
    "ResearchEnvironmentKind": ("synth_ai.sdk.research.contracts", "EnvironmentKind"),
    "ResearchFactoriesAPI": ("synth_ai.sdk.research.factories", "ResearchFactoriesAPI"),
    "ResearchHostKind": ("synth_ai.sdk.research.contracts", "HostKind"),
    "ResearchInsufficientCreditsError": (
        "synth_ai.sdk.research.errors",
        "ResearchInsufficientCreditsError",
    ),
    "ResearchLimitExceededError": (
        "synth_ai.sdk.research.errors",
        "ResearchLimitExceededError",
    ),
    "ResearchLimitsAPI": ("synth_ai.sdk.research.economics", "ResearchLimitsAPI"),
    "ResearchOrgLimits": ("synth_ai.sdk.research.models", "ResearchOrgLimits"),
    "ResearchProject": ("synth_ai.sdk.research.contracts", "ResearchProject"),
    "ResearchProjectCreateRequest": (
        "synth_ai.sdk.research.contracts",
        "ResearchProjectCreateRequest",
    ),
    "ResearchProjectPatchRequest": (
        "synth_ai.sdk.research.contracts",
        "ResearchProjectPatchRequest",
    ),
    "ResearchProjectEconomics": (
        "synth_ai.sdk.research.models",
        "ResearchProjectEconomics",
    ),
    "ResearchProjectMonthlyBudgetExhaustedError": (
        "synth_ai.sdk.research.errors",
        "ResearchProjectMonthlyBudgetExhaustedError",
    ),
    "ResearchProjectsAPI": ("synth_ai.sdk.research.projects", "ResearchProjectsAPI"),
    "ResearchRoleBinding": ("synth_ai.sdk.research.models", "ResearchRoleBinding"),
    "ResearchRoleBindings": ("synth_ai.sdk.research.models", "ResearchRoleBindings"),
    "ResearchRun": ("synth_ai.sdk.research.models", "ResearchRun"),
    "ResearchRunHandle": ("synth_ai.sdk.research.advanced_swarms", "ResearchRunHandle"),
    "ResearchRunLaunchRequest": (
        "synth_ai.sdk.research.contracts",
        "ResearchRunLaunchRequest",
    ),
    "ResearchRunProgress": ("synth_ai.sdk.research.models", "ResearchRunProgress"),
    "ResearchRunSession": ("synth_ai.sdk.research.advanced_swarms", "ResearchRunSession"),
    "ResearchRunbookPreset": ("synth_ai.sdk.research.models", "ResearchRunbookPreset"),
    "ResearchRunnableProjectRequest": (
        "synth_ai.sdk.research.contracts",
        "ResearchProjectCreateRequest",
    ),
    "ResearchRunsAPI": ("synth_ai.sdk.research.advanced_swarms", "ResearchRunsAPI"),
    "ResearchRuntimeKind": ("synth_ai.sdk.research.contracts", "RuntimeKind"),
    "ResearchSecretsAPI": ("synth_ai.sdk.research.secrets", "ResearchSecretsAPI"),
    "ResearchStructuredDenialError": (
        "synth_ai.sdk.research.errors",
        "ResearchStructuredDenialError",
    ),
    "ResearchSwarm": ("synth_ai.sdk.research.contracts", "ResearchSwarm"),
    "ResearchSwarmBranchRequest": (
        "synth_ai.sdk.research.contracts",
        "ResearchSwarmBranchRequest",
    ),
    "ResearchSwarmBranchResult": (
        "synth_ai.sdk.research.contracts",
        "ResearchSwarmBranchResult",
    ),
    "ResearchSwarmHandle": ("synth_ai.sdk.research.swarms", "ResearchSwarmHandle"),
    "ResearchSwarmLaunchRequest": (
        "synth_ai.sdk.research.contracts",
        "ResearchSwarmLaunchRequest",
    ),
    "ResearchSwarmPreflight": (
        "synth_ai.sdk.research.contracts",
        "ResearchSwarmPreflight",
    ),
    "ResearchSwarmState": ("synth_ai.sdk.research.contracts", "ResearchSwarmState"),
    "ResearchSwarmsAPI": ("synth_ai.sdk.research.swarms", "ResearchSwarmsAPI"),
    "ResearchTagSessionCreateRequest": (
        "synth_ai.sdk.research.models",
        "ResearchTagSessionCreateRequest",
    ),
    "ResearchWorkMode": ("synth_ai.sdk.research.contracts", "WorkMode"),
    "ResearchWorkerRolePalette": (
        "synth_ai.sdk.research.models",
        "ResearchWorkerRolePalette",
    ),
    "ResearchWorkProduct": ("synth_ai.sdk.research.models", "ResearchWorkProduct"),
    "ResourceLimit": ("synth_ai.sdk.research.contracts", "ResourceLimit"),
}


def __getattr__(name: str) -> object:
    target = _COMPATIBILITY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attribute = target
    value = getattr(importlib.import_module(module_name), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
