"""Typed public Research wire contracts."""

from synth_ai.core.research.contracts.common import (
    EffortId,
    EnvironmentKind,
    OrganizationId,
    PoolId,
    ProfileId,
    ProjectId,
    RuntimeKind,
    SwarmId,
)
from synth_ai.core.research.contracts.economics import (
    ResearchBillingCatalog,
    ResearchBillingDrawdown,
    ResearchBillingEntitlements,
    ResearchBillingPlan,
    ResearchOrgLimits,
    ResearchProjectEconomics,
)
from synth_ai.core.research.contracts.projects import (
    ProjectSetupState,
    ResearchProject,
    ResearchProjectCreateRequest,
    ResearchProjectPatchRequest,
    ResearchProjectSetup,
)
from synth_ai.core.research.contracts.swarms import (
    ActorHarness,
    ActorModel,
    ActorModelAssignment,
    ActorSubtype,
    ActorType,
    BranchMode,
    EnvironmentVariable,
    ExecutionCapability,
    ExecutionProfile,
    HostKind,
    KickoffMessage,
    KickoffMessageMode,
    LocalExecution,
    ProviderBinding,
    ResearchSwarm,
    ResearchSwarmBranchRequest,
    ResearchSwarmBranchResult,
    ResearchSwarmLaunchRequest,
    ResearchSwarmPreflight,
    ResearchSwarmState,
    ResourceLimit,
    ResourceProvider,
    Runbook,
    WorkMode,
)

ResearchRunLaunchRequest = ResearchSwarmLaunchRequest

__all__ = [
    "ActorHarness",
    "ActorModel",
    "ActorModelAssignment",
    "ActorSubtype",
    "ActorType",
    "BranchMode",
    "EnvironmentVariable",
    "ExecutionCapability",
    "ExecutionProfile",
    "HostKind",
    "EffortId",
    "EnvironmentKind",
    "OrganizationId",
    "KickoffMessage",
    "KickoffMessageMode",
    "LocalExecution",
    "PoolId",
    "ProfileId",
    "ProviderBinding",
    "ProjectId",
    "ProjectSetupState",
    "ResearchProject",
    "ResearchBillingCatalog",
    "ResearchBillingDrawdown",
    "ResearchBillingEntitlements",
    "ResearchBillingPlan",
    "ResearchOrgLimits",
    "ResearchProjectEconomics",
    "ResearchProjectCreateRequest",
    "ResearchProjectPatchRequest",
    "ResearchProjectSetup",
    "ResearchRunLaunchRequest",
    "ResearchSwarm",
    "ResearchSwarmBranchRequest",
    "ResearchSwarmBranchResult",
    "ResearchSwarmLaunchRequest",
    "ResearchSwarmPreflight",
    "ResearchSwarmState",
    "ResourceLimit",
    "ResourceProvider",
    "Runbook",
    "RuntimeKind",
    "SwarmId",
    "WorkMode",
]
