"""Typed public Research wire contracts."""

from __future__ import annotations

import importlib

from synth_ai.core.research.contracts.common import (
    EffortId,
    EnvironmentKind,
    FactoryId,
    OrganizationId,
    PoolId,
    ProfileId,
    ProjectId,
    RuntimeKind,
    SwarmId,
)
from synth_ai.core.research.contracts.factories import (
    BudgetPolicy,
    CapacityPolicy,
    Effort,
    EffortCreateRequest,
    EffortPatch,
    EffortPatchRequest,
    EffortRecurrence,
    EffortSpec,
    EffortStatus,
    EffortType,
    Factory,
    FactoryCreateRequest,
    FactoryCreateState,
    FactoryKind,
    FactoryLifecycleState,
    FactoryPatch,
    FactoryPatchRequest,
    FactorySpec,
    FactoryTransition,
    FactoryTransitionDecision,
    FactoryTransitionRequest,
    FactoryTransitionResponse,
    FactoryTransitionResult,
)
from synth_ai.core.research.contracts.projects import (
    Project,
    ProjectPatch,
    ProjectSetup,
    ProjectSpec,
    ProjectSetupState,
    ResearchProject,
    ResearchProjectCreateRequest,
    ResearchProjectPatchRequest,
    ResearchProjectSetup,
)
from synth_ai.core.research.contracts.swarms import (
    ActorHarness,
    ActorModel,
    ActorModelAssignment,
    ActorSubtype,
    ActorType,
    BranchMode,
    EnvironmentVariable,
    ExecutionCapability,
    ExecutionProfile,
    HostKind,
    KickoffMessage,
    KickoffMessageMode,
    LocalExecution,
    ProviderBinding,
    BranchResult,
    BranchSpec,
    ResearchSwarm,
    ResearchSwarmBranchRequest,
    ResearchSwarmBranchResult,
    ResearchSwarmLaunchRequest,
    ResearchSwarmPreflight,
    ResearchSwarmState,
    ResourceLimit,
    ResourceProvider,
    Runbook,
    Swarm,
    SwarmPreflight,
    SwarmSpec,
    SwarmState,
    WorkMode,
)

ResearchRunLaunchRequest = ResearchSwarmLaunchRequest

_ECONOMICS_EXPORTS = frozenset(
    {
        "ResearchBillingCatalog",
        "ResearchBillingDrawdown",
        "ResearchBillingEntitlements",
        "ResearchBillingPlan",
        "ResearchOrgLimits",
        "ResearchProjectEconomics",
    }
)


def __getattr__(name: str) -> object:
    if name not in _ECONOMICS_EXPORTS:
        raise AttributeError(name)
    value = getattr(
        importlib.import_module("synth_ai.core.research.contracts.economics"),
        name,
    )
    globals()[name] = value
    return value

__all__ = [
    "ActorHarness",
    "ActorModel",
    "ActorModelAssignment",
    "ActorSubtype",
    "ActorType",
    "BranchMode",
    "BranchResult",
    "BranchSpec",
    "BudgetPolicy",
    "CapacityPolicy",
    "EnvironmentVariable",
    "Effort",
    "EffortCreateRequest",
    "EffortPatch",
    "EffortPatchRequest",
    "EffortRecurrence",
    "EffortSpec",
    "EffortStatus",
    "EffortType",
    "ExecutionCapability",
    "ExecutionProfile",
    "HostKind",
    "Factory",
    "FactoryCreateRequest",
    "FactoryCreateState",
    "FactoryId",
    "FactoryKind",
    "FactoryLifecycleState",
    "FactoryPatch",
    "FactoryPatchRequest",
    "FactorySpec",
    "FactoryTransition",
    "FactoryTransitionDecision",
    "FactoryTransitionRequest",
    "FactoryTransitionResponse",
    "FactoryTransitionResult",
    "EffortId",
    "EnvironmentKind",
    "OrganizationId",
    "KickoffMessage",
    "KickoffMessageMode",
    "LocalExecution",
    "PoolId",
    "ProfileId",
    "ProviderBinding",
    "ProjectId",
    "Project",
    "ProjectPatch",
    "ProjectSetup",
    "ProjectSpec",
    "ProjectSetupState",
    "ResearchProject",
    "ResearchBillingCatalog",
    "ResearchBillingDrawdown",
    "ResearchBillingEntitlements",
    "ResearchBillingPlan",
    "ResearchOrgLimits",
    "ResearchProjectEconomics",
    "ResearchProjectCreateRequest",
    "ResearchProjectPatchRequest",
    "ResearchProjectSetup",
    "ResearchRunLaunchRequest",
    "ResearchSwarm",
    "ResearchSwarmBranchRequest",
    "ResearchSwarmBranchResult",
    "ResearchSwarmLaunchRequest",
    "ResearchSwarmPreflight",
    "ResearchSwarmState",
    "ResourceLimit",
    "ResourceProvider",
    "Runbook",
    "RuntimeKind",
    "SwarmId",
    "Swarm",
    "SwarmPreflight",
    "SwarmSpec",
    "SwarmState",
    "WorkMode",
]
